apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pgbouncer.fullname" . }}-config
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
data:
  pgbouncer.ini: |
    [databases]
    {{ .Values.database.name }} = host={{ .Values.database.host }} port={{ .Values.database.port }} dbname={{ .Values.database.name }}

    [pgbouncer]
    listen_addr = 0.0.0.0
    listen_port = {{ .Values.pgbouncer.listenPort }}
    auth_type = md5
    auth_file = /etc/pgbouncer/userlist.txt
    pool_mode = {{ .Values.pgbouncer.poolMode }}
    max_client_conn = {{ .Values.pgbouncer.maxClientConn }}
    default_pool_size = {{ .Values.pgbouncer.defaultPoolSize }}
    min_pool_size = {{ .Values.pgbouncer.minPoolSize }}
    reserve_pool_size = {{ .Values.pgbouncer.reservePoolSize }}
    admin_users = {{ .Values.database.user }}
    stats_users = {{ .Values.database.user }}
