apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pgbouncer.fullname" . }}
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pgbouncer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pgbouncer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: pgbouncer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: pgbouncer
              containerPort: {{ .Values.pgbouncer.listenPort }}
              protocol: TCP
          env:
            - name: PGBOUNCER_DATABASE
              value: {{ .Values.database.name | quote }}
            - name: POSTGRESQL_HOST
              value: {{ .Values.database.host | quote }}
            - name: POSTGRESQL_PORT
              value: {{ .Values.database.port | quote }}
            - name: POSTGRESQL_USERNAME
              value: {{ .Values.database.user | quote }}
            - name: POSTGRESQL_PASSWORD
              value: {{ .Values.database.password | quote }}
            - name: PGBOUNCER_PORT
              value: {{ .Values.pgbouncer.listenPort | quote }}
            - name: PGBOUNCER_POOL_MODE
              value: {{ .Values.pgbouncer.poolMode | quote }}
            - name: PGBOUNCER_MAX_CLIENT_CONN
              value: {{ .Values.pgbouncer.maxClientConn | quote }}
            - name: PGBOUNCER_DEFAULT_POOL_SIZE
              value: {{ .Values.pgbouncer.defaultPoolSize | quote }}
            - name: PGBOUNCER_MIN_POOL_SIZE
              value: {{ .Values.pgbouncer.minPoolSize | quote }}
            - name: PGBOUNCER_RESERVE_POOL_SIZE
              value: {{ .Values.pgbouncer.reservePoolSize | quote }}
            - name: PGBOUNCER_AUTH_TYPE
              value: "md5"
          livenessProbe:
            tcpSocket:
              port: {{ .Values.pgbouncer.listenPort }}
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: {{ .Values.pgbouncer.listenPort }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
