apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgbouncer.fullname" . }}-secret
  labels:
    {{- include "pgbouncer.labels" . | nindent 4 }}
type: Opaque
data:
  userlist.txt: {{ printf "\"%s\" \"%s\"" .Values.database.user .Values.database.password | b64enc | quote }}
