// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * ClassroomCreate
 */
export type ClassroomCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Building
     */
    building?: string | null;
    /**
     * Capacity
     */
    capacity?: number | null;
};

/**
 * ClassroomResponse
 */
export type ClassroomResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Building
     */
    building: string | null;
    /**
     * Capacity
     */
    capacity: number | null;
};

/**
 * ClassroomUpdate
 */
export type ClassroomUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Building
     */
    building?: string | null;
    /**
     * Capacity
     */
    capacity?: number | null;
};

/**
 * DaySchedule
 */
export type DaySchedule = {
    /**
     * Date
     */
    date: string;
    /**
     * Day Of Week
     */
    day_of_week: number;
    /**
     * Day Name
     */
    day_name: string;
    /**
     * Lessons
     */
    lessons: Array<LessonSlot>;
};

/**
 * DayTemplate
 */
export type DayTemplate = {
    /**
     * Day Of Week
     */
    day_of_week: number;
    /**
     * Day Name
     */
    day_name: string;
    /**
     * Slots
     */
    slots: Array<TemplateSlotResponse>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LessonSlot
 */
export type LessonSlot = {
    /**
     * Slot Number
     */
    slot_number: number | null;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string;
    /**
     * Subject Name
     */
    subject_name: string;
    /**
     * Lesson Type
     */
    lesson_type: string;
    /**
     * Teacher Name
     */
    teacher_name: string | null;
    /**
     * Group Name
     */
    group_name: string;
    /**
     * Classroom Name
     */
    classroom_name: string | null;
    /**
     * Is Override
     */
    is_override?: boolean;
    /**
     * Override Comment
     */
    override_comment?: string | null;
};

/**
 * OverrideCreate
 */
export type OverrideCreate = {
    /**
     * Semester Id
     */
    semester_id: string;
    /**
     * Date
     */
    date: string;
    /**
     * Slot Number
     */
    slot_number: number;
    /**
     * Group Name
     */
    group_name: string;
    /**
     * Action
     */
    action: string;
    /**
     * New Subject Name
     */
    new_subject_name?: string | null;
    /**
     * New Lesson Type
     */
    new_lesson_type?: string | null;
    /**
     * New Teacher Name
     */
    new_teacher_name?: string | null;
    /**
     * New Classroom Name
     */
    new_classroom_name?: string | null;
    /**
     * New Start Time
     */
    new_start_time?: string | null;
    /**
     * New End Time
     */
    new_end_time?: string | null;
    /**
     * Comment
     */
    comment?: string | null;
};

/**
 * OverrideResponse
 */
export type OverrideResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Semester Id
     */
    semester_id: string;
    /**
     * Date
     */
    date: string;
    /**
     * Slot Number
     */
    slot_number: number;
    /**
     * Group Name
     */
    group_name: string;
    /**
     * Action
     */
    action: string;
    /**
     * New Subject Name
     */
    new_subject_name: string | null;
    /**
     * New Lesson Type
     */
    new_lesson_type: string | null;
    /**
     * New Teacher Name
     */
    new_teacher_name: string | null;
    /**
     * New Classroom Name
     */
    new_classroom_name: string | null;
    /**
     * New Start Time
     */
    new_start_time: string | null;
    /**
     * New End Time
     */
    new_end_time: string | null;
    /**
     * Comment
     */
    comment: string | null;
};

/**
 * OverrideUpdate
 */
export type OverrideUpdate = {
    /**
     * Date
     */
    date?: string | null;
    /**
     * Slot Number
     */
    slot_number?: number | null;
    /**
     * Group Name
     */
    group_name?: string | null;
    /**
     * Action
     */
    action?: string | null;
    /**
     * New Subject Name
     */
    new_subject_name?: string | null;
    /**
     * New Lesson Type
     */
    new_lesson_type?: string | null;
    /**
     * New Teacher Name
     */
    new_teacher_name?: string | null;
    /**
     * New Classroom Name
     */
    new_classroom_name?: string | null;
    /**
     * New Start Time
     */
    new_start_time?: string | null;
    /**
     * New End Time
     */
    new_end_time?: string | null;
    /**
     * Comment
     */
    comment?: string | null;
};

/**
 * SemesterCreate
 */
export type SemesterCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Cycle Anchor Date
     */
    cycle_anchor_date: string;
    /**
     * Is Active
     */
    is_active?: boolean;
};

/**
 * SemesterResponse
 */
export type SemesterResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Start Date
     */
    start_date: string;
    /**
     * End Date
     */
    end_date: string;
    /**
     * Cycle Anchor Date
     */
    cycle_anchor_date: string;
    /**
     * Is Active
     */
    is_active: boolean;
};

/**
 * SemesterUpdate
 */
export type SemesterUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Start Date
     */
    start_date?: string | null;
    /**
     * End Date
     */
    end_date?: string | null;
    /**
     * Cycle Anchor Date
     */
    cycle_anchor_date?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
};

/**
 * SessionEventCreate
 */
export type SessionEventCreate = {
    /**
     * Semester Id
     */
    semester_id: string;
    /**
     * Date
     */
    date: string;
    /**
     * Slot Number
     */
    slot_number?: number | null;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string;
    /**
     * Subject Name
     */
    subject_name: string;
    /**
     * Lesson Type
     */
    lesson_type: string;
    /**
     * Teacher Name
     */
    teacher_name?: string | null;
    /**
     * Group Name
     */
    group_name: string;
    /**
     * Classroom Name
     */
    classroom_name?: string | null;
};

/**
 * SessionEventResponse
 */
export type SessionEventResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Semester Id
     */
    semester_id: string;
    /**
     * Date
     */
    date: string;
    /**
     * Slot Number
     */
    slot_number: number | null;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string;
    /**
     * Subject Name
     */
    subject_name: string;
    /**
     * Lesson Type
     */
    lesson_type: string;
    /**
     * Teacher Name
     */
    teacher_name: string | null;
    /**
     * Group Name
     */
    group_name: string;
    /**
     * Classroom Name
     */
    classroom_name: string | null;
};

/**
 * SessionEventUpdate
 */
export type SessionEventUpdate = {
    /**
     * Date
     */
    date?: string | null;
    /**
     * Slot Number
     */
    slot_number?: number | null;
    /**
     * Start Time
     */
    start_time?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Subject Name
     */
    subject_name?: string | null;
    /**
     * Lesson Type
     */
    lesson_type?: string | null;
    /**
     * Teacher Name
     */
    teacher_name?: string | null;
    /**
     * Group Name
     */
    group_name?: string | null;
    /**
     * Classroom Name
     */
    classroom_name?: string | null;
};

/**
 * TemplateResponse
 */
export type TemplateResponse = {
    /**
     * Semester Id
     */
    semester_id: string;
    /**
     * Semester Name
     */
    semester_name: string;
    /**
     * Week 1
     */
    week_1: Array<DayTemplate>;
    /**
     * Week 2
     */
    week_2: Array<DayTemplate>;
};

/**
 * TemplateSlotBulkCreate
 */
export type TemplateSlotBulkCreate = {
    /**
     * Items
     */
    items: Array<TemplateSlotCreate>;
};

/**
 * TemplateSlotCreate
 */
export type TemplateSlotCreate = {
    /**
     * Semester Id
     */
    semester_id: string;
    /**
     * Week Number
     */
    week_number: number;
    /**
     * Day Of Week
     */
    day_of_week: number;
    /**
     * Slot Number
     */
    slot_number: number;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string;
    /**
     * Subject Name
     */
    subject_name: string;
    /**
     * Lesson Type
     */
    lesson_type: string;
    /**
     * Teacher Name
     */
    teacher_name?: string | null;
    /**
     * Group Name
     */
    group_name: string;
    /**
     * Classroom Name
     */
    classroom_name?: string | null;
};

/**
 * TemplateSlotResponse
 */
export type TemplateSlotResponse = {
    /**
     * Id
     */
    id: string;
    /**
     * Semester Id
     */
    semester_id: string;
    /**
     * Week Number
     */
    week_number: number;
    /**
     * Day Of Week
     */
    day_of_week: number;
    /**
     * Slot Number
     */
    slot_number: number;
    /**
     * Start Time
     */
    start_time: string;
    /**
     * End Time
     */
    end_time: string;
    /**
     * Subject Name
     */
    subject_name: string;
    /**
     * Lesson Type
     */
    lesson_type: string;
    /**
     * Teacher Name
     */
    teacher_name: string | null;
    /**
     * Group Name
     */
    group_name: string;
    /**
     * Classroom Name
     */
    classroom_name: string | null;
};

/**
 * TemplateSlotUpdate
 */
export type TemplateSlotUpdate = {
    /**
     * Week Number
     */
    week_number?: number | null;
    /**
     * Day Of Week
     */
    day_of_week?: number | null;
    /**
     * Slot Number
     */
    slot_number?: number | null;
    /**
     * Start Time
     */
    start_time?: string | null;
    /**
     * End Time
     */
    end_time?: string | null;
    /**
     * Subject Name
     */
    subject_name?: string | null;
    /**
     * Lesson Type
     */
    lesson_type?: string | null;
    /**
     * Teacher Name
     */
    teacher_name?: string | null;
    /**
     * Group Name
     */
    group_name?: string | null;
    /**
     * Classroom Name
     */
    classroom_name?: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type GetStatusStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/status';
};

export type GetStatusStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GroupScheduleGroupsGroupNameScheduleGetData = {
    body?: never;
    path: {
        /**
         * Group Name
         */
        group_name: string;
    };
    query: {
        /**
         * Date From
         */
        date_from: string;
        /**
         * Date To
         */
        date_to: string;
        /**
         * Semester Id
         */
        semester_id?: string | null;
    };
    url: '/groups/{group_name}/schedule';
};

export type GroupScheduleGroupsGroupNameScheduleGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GroupScheduleGroupsGroupNameScheduleGetError = GroupScheduleGroupsGroupNameScheduleGetErrors[keyof GroupScheduleGroupsGroupNameScheduleGetErrors];

export type GroupScheduleGroupsGroupNameScheduleGetResponses = {
    /**
     * Response Group Schedule Groups  Group Name  Schedule Get
     *
     * Successful Response
     */
    200: Array<DaySchedule>;
};

export type GroupScheduleGroupsGroupNameScheduleGetResponse = GroupScheduleGroupsGroupNameScheduleGetResponses[keyof GroupScheduleGroupsGroupNameScheduleGetResponses];

export type GroupExamsGroupsGroupNameExamsGetData = {
    body?: never;
    path: {
        /**
         * Group Name
         */
        group_name: string;
    };
    query?: {
        /**
         * Semester Id
         */
        semester_id?: string | null;
    };
    url: '/groups/{group_name}/exams';
};

export type GroupExamsGroupsGroupNameExamsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GroupExamsGroupsGroupNameExamsGetError = GroupExamsGroupsGroupNameExamsGetErrors[keyof GroupExamsGroupsGroupNameExamsGetErrors];

export type GroupExamsGroupsGroupNameExamsGetResponses = {
    /**
     * Response Group Exams Groups  Group Name  Exams Get
     *
     * Successful Response
     */
    200: Array<SessionEventResponse>;
};

export type GroupExamsGroupsGroupNameExamsGetResponse = GroupExamsGroupsGroupNameExamsGetResponses[keyof GroupExamsGroupsGroupNameExamsGetResponses];

export type GroupTemplateGroupsGroupNameTemplateGetData = {
    body?: never;
    path: {
        /**
         * Group Name
         */
        group_name: string;
    };
    query?: {
        /**
         * Semester Id
         */
        semester_id?: string | null;
    };
    url: '/groups/{group_name}/template';
};

export type GroupTemplateGroupsGroupNameTemplateGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GroupTemplateGroupsGroupNameTemplateGetError = GroupTemplateGroupsGroupNameTemplateGetErrors[keyof GroupTemplateGroupsGroupNameTemplateGetErrors];

export type GroupTemplateGroupsGroupNameTemplateGetResponses = {
    /**
     * Successful Response
     */
    200: TemplateResponse;
};

export type GroupTemplateGroupsGroupNameTemplateGetResponse = GroupTemplateGroupsGroupNameTemplateGetResponses[keyof GroupTemplateGroupsGroupNameTemplateGetResponses];

export type TeacherScheduleTeachersTeacherNameScheduleGetData = {
    body?: never;
    path: {
        /**
         * Teacher Name
         */
        teacher_name: string;
    };
    query: {
        /**
         * Date From
         */
        date_from: string;
        /**
         * Date To
         */
        date_to: string;
        /**
         * Semester Id
         */
        semester_id?: string | null;
    };
    url: '/teachers/{teacher_name}/schedule';
};

export type TeacherScheduleTeachersTeacherNameScheduleGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeacherScheduleTeachersTeacherNameScheduleGetError = TeacherScheduleTeachersTeacherNameScheduleGetErrors[keyof TeacherScheduleTeachersTeacherNameScheduleGetErrors];

export type TeacherScheduleTeachersTeacherNameScheduleGetResponses = {
    /**
     * Response Teacher Schedule Teachers  Teacher Name  Schedule Get
     *
     * Successful Response
     */
    200: Array<DaySchedule>;
};

export type TeacherScheduleTeachersTeacherNameScheduleGetResponse = TeacherScheduleTeachersTeacherNameScheduleGetResponses[keyof TeacherScheduleTeachersTeacherNameScheduleGetResponses];

export type TeacherExamsTeachersTeacherNameExamsGetData = {
    body?: never;
    path: {
        /**
         * Teacher Name
         */
        teacher_name: string;
    };
    query?: {
        /**
         * Semester Id
         */
        semester_id?: string | null;
    };
    url: '/teachers/{teacher_name}/exams';
};

export type TeacherExamsTeachersTeacherNameExamsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeacherExamsTeachersTeacherNameExamsGetError = TeacherExamsTeachersTeacherNameExamsGetErrors[keyof TeacherExamsTeachersTeacherNameExamsGetErrors];

export type TeacherExamsTeachersTeacherNameExamsGetResponses = {
    /**
     * Response Teacher Exams Teachers  Teacher Name  Exams Get
     *
     * Successful Response
     */
    200: Array<SessionEventResponse>;
};

export type TeacherExamsTeachersTeacherNameExamsGetResponse = TeacherExamsTeachersTeacherNameExamsGetResponses[keyof TeacherExamsTeachersTeacherNameExamsGetResponses];

export type TeacherTemplateTeachersTeacherNameTemplateGetData = {
    body?: never;
    path: {
        /**
         * Teacher Name
         */
        teacher_name: string;
    };
    query?: {
        /**
         * Semester Id
         */
        semester_id?: string | null;
    };
    url: '/teachers/{teacher_name}/template';
};

export type TeacherTemplateTeachersTeacherNameTemplateGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TeacherTemplateTeachersTeacherNameTemplateGetError = TeacherTemplateTeachersTeacherNameTemplateGetErrors[keyof TeacherTemplateTeachersTeacherNameTemplateGetErrors];

export type TeacherTemplateTeachersTeacherNameTemplateGetResponses = {
    /**
     * Successful Response
     */
    200: TemplateResponse;
};

export type TeacherTemplateTeachersTeacherNameTemplateGetResponse = TeacherTemplateTeachersTeacherNameTemplateGetResponses[keyof TeacherTemplateTeachersTeacherNameTemplateGetResponses];

export type ListClassroomsAdminClassroomsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/admin/classrooms';
};

export type ListClassroomsAdminClassroomsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListClassroomsAdminClassroomsGetError = ListClassroomsAdminClassroomsGetErrors[keyof ListClassroomsAdminClassroomsGetErrors];

export type ListClassroomsAdminClassroomsGetResponses = {
    /**
     * Response List Classrooms Admin Classrooms Get
     *
     * Successful Response
     */
    200: Array<ClassroomResponse>;
};

export type ListClassroomsAdminClassroomsGetResponse = ListClassroomsAdminClassroomsGetResponses[keyof ListClassroomsAdminClassroomsGetResponses];

export type CreateClassroomAdminClassroomsPostData = {
    body: ClassroomCreate;
    path?: never;
    query?: never;
    url: '/admin/classrooms';
};

export type CreateClassroomAdminClassroomsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateClassroomAdminClassroomsPostError = CreateClassroomAdminClassroomsPostErrors[keyof CreateClassroomAdminClassroomsPostErrors];

export type CreateClassroomAdminClassroomsPostResponses = {
    /**
     * Successful Response
     */
    201: ClassroomResponse;
};

export type CreateClassroomAdminClassroomsPostResponse = CreateClassroomAdminClassroomsPostResponses[keyof CreateClassroomAdminClassroomsPostResponses];

export type DeleteClassroomAdminClassroomsClassroomIdDeleteData = {
    body?: never;
    path: {
        /**
         * Classroom Id
         */
        classroom_id: string;
    };
    query?: never;
    url: '/admin/classrooms/{classroom_id}';
};

export type DeleteClassroomAdminClassroomsClassroomIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteClassroomAdminClassroomsClassroomIdDeleteError = DeleteClassroomAdminClassroomsClassroomIdDeleteErrors[keyof DeleteClassroomAdminClassroomsClassroomIdDeleteErrors];

export type DeleteClassroomAdminClassroomsClassroomIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetClassroomAdminClassroomsClassroomIdGetData = {
    body?: never;
    path: {
        /**
         * Classroom Id
         */
        classroom_id: string;
    };
    query?: never;
    url: '/admin/classrooms/{classroom_id}';
};

export type GetClassroomAdminClassroomsClassroomIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetClassroomAdminClassroomsClassroomIdGetError = GetClassroomAdminClassroomsClassroomIdGetErrors[keyof GetClassroomAdminClassroomsClassroomIdGetErrors];

export type GetClassroomAdminClassroomsClassroomIdGetResponses = {
    /**
     * Successful Response
     */
    200: ClassroomResponse;
};

export type GetClassroomAdminClassroomsClassroomIdGetResponse = GetClassroomAdminClassroomsClassroomIdGetResponses[keyof GetClassroomAdminClassroomsClassroomIdGetResponses];

export type UpdateClassroomAdminClassroomsClassroomIdPutData = {
    body: ClassroomUpdate;
    path: {
        /**
         * Classroom Id
         */
        classroom_id: string;
    };
    query?: never;
    url: '/admin/classrooms/{classroom_id}';
};

export type UpdateClassroomAdminClassroomsClassroomIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateClassroomAdminClassroomsClassroomIdPutError = UpdateClassroomAdminClassroomsClassroomIdPutErrors[keyof UpdateClassroomAdminClassroomsClassroomIdPutErrors];

export type UpdateClassroomAdminClassroomsClassroomIdPutResponses = {
    /**
     * Successful Response
     */
    200: ClassroomResponse;
};

export type UpdateClassroomAdminClassroomsClassroomIdPutResponse = UpdateClassroomAdminClassroomsClassroomIdPutResponses[keyof UpdateClassroomAdminClassroomsClassroomIdPutResponses];

export type ListSemestersAdminSemestersGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/admin/semesters';
};

export type ListSemestersAdminSemestersGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSemestersAdminSemestersGetError = ListSemestersAdminSemestersGetErrors[keyof ListSemestersAdminSemestersGetErrors];

export type ListSemestersAdminSemestersGetResponses = {
    /**
     * Response List Semesters Admin Semesters Get
     *
     * Successful Response
     */
    200: Array<SemesterResponse>;
};

export type ListSemestersAdminSemestersGetResponse = ListSemestersAdminSemestersGetResponses[keyof ListSemestersAdminSemestersGetResponses];

export type CreateSemesterAdminSemestersPostData = {
    body: SemesterCreate;
    path?: never;
    query?: never;
    url: '/admin/semesters';
};

export type CreateSemesterAdminSemestersPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSemesterAdminSemestersPostError = CreateSemesterAdminSemestersPostErrors[keyof CreateSemesterAdminSemestersPostErrors];

export type CreateSemesterAdminSemestersPostResponses = {
    /**
     * Successful Response
     */
    201: SemesterResponse;
};

export type CreateSemesterAdminSemestersPostResponse = CreateSemesterAdminSemestersPostResponses[keyof CreateSemesterAdminSemestersPostResponses];

export type DeleteSemesterAdminSemestersSemesterIdDeleteData = {
    body?: never;
    path: {
        /**
         * Semester Id
         */
        semester_id: string;
    };
    query?: never;
    url: '/admin/semesters/{semester_id}';
};

export type DeleteSemesterAdminSemestersSemesterIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSemesterAdminSemestersSemesterIdDeleteError = DeleteSemesterAdminSemestersSemesterIdDeleteErrors[keyof DeleteSemesterAdminSemestersSemesterIdDeleteErrors];

export type DeleteSemesterAdminSemestersSemesterIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetSemesterAdminSemestersSemesterIdGetData = {
    body?: never;
    path: {
        /**
         * Semester Id
         */
        semester_id: string;
    };
    query?: never;
    url: '/admin/semesters/{semester_id}';
};

export type GetSemesterAdminSemestersSemesterIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetSemesterAdminSemestersSemesterIdGetError = GetSemesterAdminSemestersSemesterIdGetErrors[keyof GetSemesterAdminSemestersSemesterIdGetErrors];

export type GetSemesterAdminSemestersSemesterIdGetResponses = {
    /**
     * Successful Response
     */
    200: SemesterResponse;
};

export type GetSemesterAdminSemestersSemesterIdGetResponse = GetSemesterAdminSemestersSemesterIdGetResponses[keyof GetSemesterAdminSemestersSemesterIdGetResponses];

export type UpdateSemesterAdminSemestersSemesterIdPutData = {
    body: SemesterUpdate;
    path: {
        /**
         * Semester Id
         */
        semester_id: string;
    };
    query?: never;
    url: '/admin/semesters/{semester_id}';
};

export type UpdateSemesterAdminSemestersSemesterIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSemesterAdminSemestersSemesterIdPutError = UpdateSemesterAdminSemestersSemesterIdPutErrors[keyof UpdateSemesterAdminSemestersSemesterIdPutErrors];

export type UpdateSemesterAdminSemestersSemesterIdPutResponses = {
    /**
     * Successful Response
     */
    200: SemesterResponse;
};

export type UpdateSemesterAdminSemestersSemesterIdPutResponse = UpdateSemesterAdminSemestersSemesterIdPutResponses[keyof UpdateSemesterAdminSemestersSemesterIdPutResponses];

export type ListTemplatesAdminTemplatesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Semester Id
         */
        semester_id: string;
        /**
         * Week Number
         */
        week_number?: number | null;
        /**
         * Day Of Week
         */
        day_of_week?: number | null;
        /**
         * Group Name
         */
        group_name?: string | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/admin/templates';
};

export type ListTemplatesAdminTemplatesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListTemplatesAdminTemplatesGetError = ListTemplatesAdminTemplatesGetErrors[keyof ListTemplatesAdminTemplatesGetErrors];

export type ListTemplatesAdminTemplatesGetResponses = {
    /**
     * Response List Templates Admin Templates Get
     *
     * Successful Response
     */
    200: Array<TemplateSlotResponse>;
};

export type ListTemplatesAdminTemplatesGetResponse = ListTemplatesAdminTemplatesGetResponses[keyof ListTemplatesAdminTemplatesGetResponses];

export type CreateTemplateAdminTemplatesPostData = {
    body: TemplateSlotCreate;
    path?: never;
    query?: never;
    url: '/admin/templates';
};

export type CreateTemplateAdminTemplatesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTemplateAdminTemplatesPostError = CreateTemplateAdminTemplatesPostErrors[keyof CreateTemplateAdminTemplatesPostErrors];

export type CreateTemplateAdminTemplatesPostResponses = {
    /**
     * Successful Response
     */
    201: TemplateSlotResponse;
};

export type CreateTemplateAdminTemplatesPostResponse = CreateTemplateAdminTemplatesPostResponses[keyof CreateTemplateAdminTemplatesPostResponses];

export type CreateTemplatesBulkAdminTemplatesBulkPostData = {
    body: TemplateSlotBulkCreate;
    path?: never;
    query?: never;
    url: '/admin/templates/bulk';
};

export type CreateTemplatesBulkAdminTemplatesBulkPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateTemplatesBulkAdminTemplatesBulkPostError = CreateTemplatesBulkAdminTemplatesBulkPostErrors[keyof CreateTemplatesBulkAdminTemplatesBulkPostErrors];

export type CreateTemplatesBulkAdminTemplatesBulkPostResponses = {
    /**
     * Response Create Templates Bulk Admin Templates Bulk Post
     *
     * Successful Response
     */
    201: Array<TemplateSlotResponse>;
};

export type CreateTemplatesBulkAdminTemplatesBulkPostResponse = CreateTemplatesBulkAdminTemplatesBulkPostResponses[keyof CreateTemplatesBulkAdminTemplatesBulkPostResponses];

export type DeleteTemplateAdminTemplatesTemplateIdDeleteData = {
    body?: never;
    path: {
        /**
         * Template Id
         */
        template_id: string;
    };
    query?: never;
    url: '/admin/templates/{template_id}';
};

export type DeleteTemplateAdminTemplatesTemplateIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteTemplateAdminTemplatesTemplateIdDeleteError = DeleteTemplateAdminTemplatesTemplateIdDeleteErrors[keyof DeleteTemplateAdminTemplatesTemplateIdDeleteErrors];

export type DeleteTemplateAdminTemplatesTemplateIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateTemplateAdminTemplatesTemplateIdPutData = {
    body: TemplateSlotUpdate;
    path: {
        /**
         * Template Id
         */
        template_id: string;
    };
    query?: never;
    url: '/admin/templates/{template_id}';
};

export type UpdateTemplateAdminTemplatesTemplateIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateTemplateAdminTemplatesTemplateIdPutError = UpdateTemplateAdminTemplatesTemplateIdPutErrors[keyof UpdateTemplateAdminTemplatesTemplateIdPutErrors];

export type UpdateTemplateAdminTemplatesTemplateIdPutResponses = {
    /**
     * Successful Response
     */
    200: TemplateSlotResponse;
};

export type UpdateTemplateAdminTemplatesTemplateIdPutResponse = UpdateTemplateAdminTemplatesTemplateIdPutResponses[keyof UpdateTemplateAdminTemplatesTemplateIdPutResponses];

export type ListOverridesAdminOverridesGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Semester Id
         */
        semester_id: string;
        /**
         * Date From
         */
        date_from?: string | null;
        /**
         * Date To
         */
        date_to?: string | null;
        /**
         * Group Name
         */
        group_name?: string | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/admin/overrides';
};

export type ListOverridesAdminOverridesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListOverridesAdminOverridesGetError = ListOverridesAdminOverridesGetErrors[keyof ListOverridesAdminOverridesGetErrors];

export type ListOverridesAdminOverridesGetResponses = {
    /**
     * Response List Overrides Admin Overrides Get
     *
     * Successful Response
     */
    200: Array<OverrideResponse>;
};

export type ListOverridesAdminOverridesGetResponse = ListOverridesAdminOverridesGetResponses[keyof ListOverridesAdminOverridesGetResponses];

export type CreateOverrideAdminOverridesPostData = {
    body: OverrideCreate;
    path?: never;
    query?: never;
    url: '/admin/overrides';
};

export type CreateOverrideAdminOverridesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateOverrideAdminOverridesPostError = CreateOverrideAdminOverridesPostErrors[keyof CreateOverrideAdminOverridesPostErrors];

export type CreateOverrideAdminOverridesPostResponses = {
    /**
     * Successful Response
     */
    201: OverrideResponse;
};

export type CreateOverrideAdminOverridesPostResponse = CreateOverrideAdminOverridesPostResponses[keyof CreateOverrideAdminOverridesPostResponses];

export type DeleteOverrideAdminOverridesOverrideIdDeleteData = {
    body?: never;
    path: {
        /**
         * Override Id
         */
        override_id: string;
    };
    query?: never;
    url: '/admin/overrides/{override_id}';
};

export type DeleteOverrideAdminOverridesOverrideIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteOverrideAdminOverridesOverrideIdDeleteError = DeleteOverrideAdminOverridesOverrideIdDeleteErrors[keyof DeleteOverrideAdminOverridesOverrideIdDeleteErrors];

export type DeleteOverrideAdminOverridesOverrideIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateOverrideAdminOverridesOverrideIdPutData = {
    body: OverrideUpdate;
    path: {
        /**
         * Override Id
         */
        override_id: string;
    };
    query?: never;
    url: '/admin/overrides/{override_id}';
};

export type UpdateOverrideAdminOverridesOverrideIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateOverrideAdminOverridesOverrideIdPutError = UpdateOverrideAdminOverridesOverrideIdPutErrors[keyof UpdateOverrideAdminOverridesOverrideIdPutErrors];

export type UpdateOverrideAdminOverridesOverrideIdPutResponses = {
    /**
     * Successful Response
     */
    200: OverrideResponse;
};

export type UpdateOverrideAdminOverridesOverrideIdPutResponse = UpdateOverrideAdminOverridesOverrideIdPutResponses[keyof UpdateOverrideAdminOverridesOverrideIdPutResponses];

export type ListSessionEventsAdminSessionEventsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Semester Id
         */
        semester_id: string;
        /**
         * Group Name
         */
        group_name?: string | null;
        /**
         * Offset
         */
        offset?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/admin/session-events';
};

export type ListSessionEventsAdminSessionEventsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListSessionEventsAdminSessionEventsGetError = ListSessionEventsAdminSessionEventsGetErrors[keyof ListSessionEventsAdminSessionEventsGetErrors];

export type ListSessionEventsAdminSessionEventsGetResponses = {
    /**
     * Response List Session Events Admin Session Events Get
     *
     * Successful Response
     */
    200: Array<SessionEventResponse>;
};

export type ListSessionEventsAdminSessionEventsGetResponse = ListSessionEventsAdminSessionEventsGetResponses[keyof ListSessionEventsAdminSessionEventsGetResponses];

export type CreateSessionEventAdminSessionEventsPostData = {
    body: SessionEventCreate;
    path?: never;
    query?: never;
    url: '/admin/session-events';
};

export type CreateSessionEventAdminSessionEventsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateSessionEventAdminSessionEventsPostError = CreateSessionEventAdminSessionEventsPostErrors[keyof CreateSessionEventAdminSessionEventsPostErrors];

export type CreateSessionEventAdminSessionEventsPostResponses = {
    /**
     * Successful Response
     */
    201: SessionEventResponse;
};

export type CreateSessionEventAdminSessionEventsPostResponse = CreateSessionEventAdminSessionEventsPostResponses[keyof CreateSessionEventAdminSessionEventsPostResponses];

export type DeleteSessionEventAdminSessionEventsEventIdDeleteData = {
    body?: never;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/admin/session-events/{event_id}';
};

export type DeleteSessionEventAdminSessionEventsEventIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteSessionEventAdminSessionEventsEventIdDeleteError = DeleteSessionEventAdminSessionEventsEventIdDeleteErrors[keyof DeleteSessionEventAdminSessionEventsEventIdDeleteErrors];

export type DeleteSessionEventAdminSessionEventsEventIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateSessionEventAdminSessionEventsEventIdPutData = {
    body: SessionEventUpdate;
    path: {
        /**
         * Event Id
         */
        event_id: string;
    };
    query?: never;
    url: '/admin/session-events/{event_id}';
};

export type UpdateSessionEventAdminSessionEventsEventIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateSessionEventAdminSessionEventsEventIdPutError = UpdateSessionEventAdminSessionEventsEventIdPutErrors[keyof UpdateSessionEventAdminSessionEventsEventIdPutErrors];

export type UpdateSessionEventAdminSessionEventsEventIdPutResponses = {
    /**
     * Successful Response
     */
    200: SessionEventResponse;
};

export type UpdateSessionEventAdminSessionEventsEventIdPutResponse = UpdateSessionEventAdminSessionEventsEventIdPutResponses[keyof UpdateSessionEventAdminSessionEventsEventIdPutResponses];
