# Generated values for frontend in production environment
# Generated at: 2025-12-01
# Source: services/frontend/service.yaml

replicaCount: 3

image:
  repository: frontend
  tag: ""
  pullPolicy: IfNotPresent

nameOverride: "frontend"
fullnameOverride: "frontend"

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

env:
  PORT: "3000"
  NODE_ENV: "production"
  NEXT_PUBLIC_BACKEND_URL: "http://84.252.134.216"

resources:
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /api/status
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5

readinessProbe:
  httpGet:
    path: /api/status
    port: http
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 10
  failureThreshold: 5

nodeSelector: {}

tolerations: []

affinity: {}

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
      - type: Pods
        value: 1
        periodSeconds: 60
      selectPolicy: Min

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 100%
