import { cwd } from 'node:process';

const collectCoverageFrom = [
  '**/*.{mjs,ts,tsx}',
  '!**/node_modules/**',
  '!**/*.d.ts',
  '!**/__reports/**',
  '!src/vendor/**',
  '!src/tools/**',
  '!src/types/graphql.ts',
  '!src/**/__mocks__/**',
  '!src/**/mocks/**',
  '!**/*.screen.spec.{ts,tsx}',
  '!**/*.stories.{ts,tsx}',
  '!**/*.lazy.{ts,tsx}',
  '!**/*.i18n/*',
  '!**/*.mock.{ts,tsx}',
  '!src/client/graphql-types.ts',
  '!**/*.graphql-types.d.ts',
  '!src/shared/api/gql/gql.ts',
  '!src/shared/api/gql/graphql.ts',
  '!**/.next/**',
  '!**/storybook-static/**',
  '!**/playwright-report/**',
  '!src/**/*.model.ts',
  '!src/**/*.module.ts',
  '!src/**/*.dto.ts',
  '!src/main.ts',
  '!instrumentation.ts',
  '!server/app.module.ts',
  '!src/types/**/*.ts',
  '!**/types.ts',
  '!**/*.config.ts',
  '!src/**/*.mock.ts',
  '!src/**/*.schema.ts',
  '!src/**/*.schemas.ts',
  '!src/server/gql/types.ts',
];

const baseJestConfig = {
  coverageProvider: 'v8',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts', '.mts'],
  moduleDirectories: ['src', 'node_modules'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'cjs', 'jsx'],
  collectCoverageFrom,
  coverageReporters: ['text', 'lcov', 'html', 'json'],
  coverageDirectory: 'coverage',
  testRegex: '.*(?<!\\.screen)\\.spec\\.[mc]?[jt]sx?$',
  rootDir: cwd(),
  preset: 'ts-jest',
  transform: {
    '^.+\\.tsx?$': ['ts-jest'],
  },
  reporters: [
    'default',
    [
      'jest-html-reporters',
      {
        publicPath: './coverage/html-report',
        filename: 'report.html',
        expand: true,
        pageTitle: 'Test Coverage Report',
        openReport: false,
        hideIcon: false,
        includeFailureMsg: true,
        includeSuiteFailure: true,
        enableMergeData: true,
        dataDirPath: './coverage/html-report/data',
        inlineSource: false,
      },
    ],
  ],
};

export default baseJestConfig;
