packages:
  - ./services/*
  - ./packages/*
  - ./e2e
lockfileIncludeTarballUrl: false
catalog:
  "@biomejs/biome": 2.2.6
  "@fastify/helmet": 12.0.1
  "@inquirer/prompts": 8.1.0
  "@nestjs/cli": 11.0.10
  "@nestjs/common": 11.1.6
  "@nestjs/config": 4.0.2
  "@nestjs/core": 11.1.6
  "@nestjs/jwt": 11.0.1
  "@nestjs/passport": 11.0.5
  "@nestjs/platform-fastify": 11.1.8
  "@nestjs/schematics": 11.0.9
  "@nestjs/testing": 11.1.6
  "@nestjs/typeorm": 11.0.0
  "@opentelemetry/api": 1.9.0
  "@opentelemetry/api-logs": 0.56.0
  "@opentelemetry/auto-instrumentations-node": 0.67.2
  "@opentelemetry/exporter-logs-otlp-http": 0.56.0
  "@opentelemetry/exporter-prometheus": 0.56.0
  "@opentelemetry/instrumentation-http": 0.56.0
  "@opentelemetry/resources": 1.30.1
  "@opentelemetry/sdk-logs": 0.56.0
  "@opentelemetry/sdk-metrics": 1.30.1
  "@opentelemetry/sdk-node": 0.56.0
  "@opentelemetry/semantic-conventions": 1.38.0
  "@playwright/test": 1.57.0
  "@testing-library/jest-dom": 6.9.1
  "@testing-library/react": 16.3.0
  "@testing-library/user-event": 14.6.1
  "@types/bcryptjs": 3.0.0
  "@types/express": 5.0.3
  "@types/handlebars": 4.1.0
  "@types/inquirer": 9.0.9
  "@types/js-cookie": 3.0.6
  "@types/node": 22.18.11
  "@types/passport-jwt": 4.0.1
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.2
  "@types/supertest": 6.0.3
  "@vitejs/plugin-react": 4.7.0
  "@vitest/coverage-v8": 2.1.9
  "@vitest/ui": 2.1.9
  baseline-browser-mapping: 2.9.11
  bcryptjs: 3.0.3
  chromium: 3.0.3
  classnames: 2.5.1
  globals: 16.4.0
  handlebars: 4.7.8
  identity-obj-proxy: 3.0.0
  inquirer: 13.1.0
  jose: 6.1.3
  js-cookie: 3.0.5
  jsdom: 25.0.1
  nestjs-security-scan: 1.1.0
  next: 16.1.1
  passport: 0.7.0
  passport-jwt: 4.0.1
  pg: 8.16.3
  prettier: 3.7.4
  react: 19.1.0
  react-dom: 19.1.0
  react-markdown: 10.1.0
  react-use: 17.6.0
  reflect-metadata: 0.2.2
  remark-gfm: 4.0.1
  rxjs: 7.8.2
  source-map-support: 0.5.21
  supertest: 7.1.4
  ts-loader: 9.5.4
  ts-node: 10.9.2
  tsconfig-paths: 4.2.0
  tsx: 4.20.6
  typeorm: 0.3.28
  typescript: 5.9.3
  unplugin-swc: 1.5.9
  vite: 6.4.1
  vitest: 2.1.9
  webpack-node-externals: 3.0.0
  yaml: 2.8.2
  zod: 4.1.13
