packages:
  - ./services/*
  - ./packages/*
  - ./e2e
lockfileIncludeTarballUrl: false
catalog:
  # Common dependencies
  '@types/node': ^22.10.7
  typescript: ^5.7.3

  # Build tools
  '@biomejs/biome': ^2.2.5
  tsx: ^4.20.6
  vite: ^6.0.7

  # Testing
  vitest: ^2.1.8
  '@vitest/coverage-v8': ^2.1.8
  '@vitest/ui': ^2.1.8
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.0
  '@testing-library/user-event': ^14.6.1
  '@vitejs/plugin-react': ^4.7.0
  identity-obj-proxy: ^3.0.0
  jsdom: ^25.0.1
  globals: ^16.0.0
  supertest: ^7.0.0
  '@types/supertest': ^6.0.2
  '@playwright/test': ^1.48.0

  # NestJS
  '@nestjs/cli': ^11.0.0
  '@nestjs/common': ^11.0.1
  '@nestjs/core': ^11.0.1
  '@nestjs/platform-fastify': ^11.0.1
  '@nestjs/schematics': ^11.0.0
  '@nestjs/testing': ^11.0.1
  reflect-metadata: ^0.2.2
  rxjs: ^7.8.1
  ts-loader: ^9.5.2
  '@types/express': ^5.0.0
  source-map-support: ^0.5.21
  ts-node: ^10.9.2
  tsconfig-paths: ^4.2.0
  unplugin-swc: ^1.5.9

  # React & Next.js
  '@types/react': ^19
  '@types/react-dom': ^19
  next: 15.5.4
  react: 19.1.0
  react-dom: 19.1.0

  # Security
  nestjs-security-scan: ^1.1.0
