config:
  maxmemory: "256mb"
  maxmemoryPolicy: "volatile-lru"
  loglevel: "notice"

persistence:
  enabled: false

resources:
  production:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 50m
      memory: 64Mi
  development:
    limits:
      cpu: 150m
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 32Mi
