import * as fs from 'node:fs';
import * as path from 'node:path';
import * as yaml from 'yaml';
import type { DatabaseValues, EnvironmentOverrides, ServiceWithDatabase } from './types';

const INFRA_DIR = path.join(__dirname, '../../');
const OVERRIDES_DIR = path.join(INFRA_DIR, 'overrides');

function getDefaultDatabaseValues(serviceName: string, dbName: string, dbUser: string): DatabaseValues {
  return {
    nameOverride: `postgresql-${serviceName}`,
    fullnameOverride: `postgresql-${serviceName}`,
    image: {
      repository: 'postgres',
      tag: '16-alpine',
      pullPolicy: 'IfNotPresent',
    },
    service: {
      type: 'ClusterIP',
      port: 5432,
    },
    persistence: {
      enabled: true,
      storageClass: '',
      size: '10Gi',
      accessMode: 'ReadWriteOnce',
    },
    resources: {
      limits: {
        cpu: '500m',
        memory: '512Mi',
      },
      requests: {
        cpu: '100m',
        memory: '256Mi',
      },
    },
    database: {
      name: dbName,
      user: dbUser,
    },
    securityContext: {
      runAsUser: 999,
      runAsGroup: 999,
      fsGroup: 999,
    },
  };
}

function getEnvironmentOverrides(serviceName: string, projectRoot: string): EnvironmentOverrides {
  // Try to read service.yaml from databases/{service}-db/ directory
  const dbServiceYamlPath = path.join(projectRoot, 'infra/databases', `${serviceName}-db/service.yaml`);
  let customResources: Record<string, unknown> | undefined;

  if (fs.existsSync(dbServiceYamlPath)) {
    const dbServiceContent = fs.readFileSync(dbServiceYamlPath, 'utf-8');
    const dbServiceConfig = yaml.parse(dbServiceContent);
    customResources = dbServiceConfig?.resources;
    console.log(`  ✓ Found database service config: infra/databases/${serviceName}-db/service.yaml`);
  }

  return {
    development: {
      persistence: {
        size: '5Gi',
      },
      resources: (customResources?.development as {
        limits: { cpu: string; memory: string };
        requests: { cpu: string; memory: string };
      }) || {
        limits: {
          cpu: '250m',
          memory: '256Mi',
        },
        requests: {
          cpu: '50m',
          memory: '128Mi',
        },
      },
    },
    production: {
      persistence: {
        size: '20Gi',
      },
      resources: (customResources?.production as {
        limits: { cpu: string; memory: string };
        requests: { cpu: string; memory: string };
      }) || {
        limits: {
          cpu: '1000m',
          memory: '1Gi',
        },
        requests: {
          cpu: '250m',
          memory: '512Mi',
        },
      },
    },
  };
}

function generateDatabaseValuesForService(service: ServiceWithDatabase): void {
  if (!service.database?.enabled) {
    return;
  }

  const serviceName = service.name;
  const projectRoot = path.join(__dirname, '../../..');

  // Read database config from infra/databases/{service}-db/service.yaml
  const dbServiceYamlPath = path.join(projectRoot, 'infra/databases', `${serviceName}-db/service.yaml`);
  let dbName = `${serviceName.replace(/-/g, '_')}_db`;
  let dbUser = `${serviceName.replace(/-/g, '_')}_user`;

  if (fs.existsSync(dbServiceYamlPath)) {
    const dbServiceContent = fs.readFileSync(dbServiceYamlPath, 'utf-8');
    const dbServiceConfig = yaml.parse(dbServiceContent);
    if (dbServiceConfig?.database) {
      dbName = dbServiceConfig.database.name || dbName;
      dbUser = dbServiceConfig.database.user || dbUser;
    }
  }

  console.log(`→ Generating database values for service: ${serviceName}`);

  // Read init script if exists
  const initScriptPath = path.join(projectRoot, 'infra/databases', `${serviceName}-db/init.sql`);
  let initScript = '';
  if (fs.existsSync(initScriptPath)) {
    initScript = fs.readFileSync(initScriptPath, 'utf-8');
    console.log(`  ✓ Found init script: infra/databases/${serviceName}-db/init.sql`);
  }

  // Generate values for each environment
  const environments = ['development', 'production'];
  const envOverrides = getEnvironmentOverrides(serviceName, projectRoot);

  for (const env of environments) {
    const baseValues = getDefaultDatabaseValues(serviceName, dbName, dbUser);
    const override = envOverrides[env as keyof EnvironmentOverrides];

    // Merge with environment-specific overrides
    const finalValues = {
      ...baseValues,
      persistence: {
        ...baseValues.persistence,
        ...override.persistence,
      },
      resources: override.resources,
      ...(initScript && { initScript }),
    };

    // Add header comment
    const header = [
      '# This file is automatically generated and should not be edited manually!',
      `# Generated database values for ${serviceName} in ${env} environment`,
      `# Database: ${dbName}`,
      `# User: ${dbUser}`,
      '',
    ].join('\n');

    const yamlContent = header + yaml.stringify(finalValues);

    // Write to file
    const envDir = path.join(OVERRIDES_DIR, env);
    if (!fs.existsSync(envDir)) {
      fs.mkdirSync(envDir, { recursive: true });
    }

    const outputPath = path.join(envDir, `postgresql-${serviceName}.yaml`);
    fs.writeFileSync(outputPath, yamlContent, 'utf-8');
    console.log(`✓ Generated: ${path.relative(process.cwd(), outputPath)}`);
  }
}

export function generateDatabaseValues(): void {
  console.log('→ Starting database values generation process');

  // Load services configuration
  const servicesPath = path.join(__dirname, '../../../services.yaml');
  const servicesContent = fs.readFileSync(servicesPath, 'utf-8');
  const servicesConfig = yaml.parse(servicesContent);

  const allServices: ServiceWithDatabase[] = [
    ...(servicesConfig.services.nest || []),
    ...(servicesConfig.services.next || []),
  ];

  const servicesWithDb = allServices.filter((s) => s.database?.enabled);

  console.log(`→ Found ${servicesWithDb.length} service(s) with database enabled:`);
  for (const service of servicesWithDb) {
    console.log(`→   • ${service.name} (${service.database?.name || `${service.name}_db`})`);
  }

  let generatedCount = 0;
  for (const service of servicesWithDb) {
    generateDatabaseValuesForService(service);
    generatedCount += 2; // development + production
  }

  console.log('→ Generation summary:');
  console.log(`✓   Total files generated: ${generatedCount}`);
}
