apiVersion: v2
name: loki
description: Grafana Loki for log aggregation
type: application
version: 1.0.0
appVersion: "3.0.0"

dependencies:
  - name: loki
    version: 6.6.4
    repository: https://grafana.github.io/helm-charts

