-- Seed mock data (core-schedule): semester
-- Generated by scripts/scrape-sut-schedule.mjs; anchor weeks 2026-03-23 / 2026-03-30

-- semester
INSERT INTO semester (id, name, start_date, end_date, cycle_anchor_date, is_active)
VALUES ('a0000000-0000-0000-0000-000000000001', 'Весна 2026', '2026-01-16', '2026-04-15', '2026-03-23', TRUE)
ON CONFLICT (id) DO NOTHING;
