FROM node:22-slim
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@9.15.0 --activate

ENV CI=1
ENV HUSKY=0

WORKDIR /app

COPY pnpm-lock.yaml pnpm-workspace.yaml tsconfig.* package.json .
RUN ls -la
COPY packages packages
COPY services/{{serviceName}} services/{{serviceName}}

WORKDIR /app/services/{{serviceName}}

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --prod --frozen-lockfile
RUN pnpm run build

CMD ["pnpm", "start"]

