import * as fs from 'node:fs';
import * as path from 'node:path';
import * as yaml from 'yaml';
import type { BaseChartValues, ServiceWithDatabase } from './types';

const INFRA_DIR = path.join(__dirname, '../../');
const OVERRIDES_DIR = path.join(INFRA_DIR, 'overrides');

function loadBaseChartValues(projectRoot: string): BaseChartValues {
  const baseValuesPath = path.join(projectRoot, 'infra/helmcharts/pgbouncer/values.yaml');

  if (!fs.existsSync(baseValuesPath)) {
    throw new Error(`Base chart values not found at: ${baseValuesPath}`);
  }

  const baseValuesContent = fs.readFileSync(baseValuesPath, 'utf-8');
  return yaml.parse(baseValuesContent) as BaseChartValues;
}

function deepMerge(
  target: Record<string, unknown>,
  source: Record<string, unknown> | undefined,
): Record<string, unknown> {
  if (!source) return target;
  const result = { ...target };
  for (const key in source) {
    if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      result[key] = deepMerge((target[key] as Record<string, unknown>) || {}, source[key] as Record<string, unknown>);
    } else if (source[key] !== undefined) {
      result[key] = source[key];
    }
  }
  return result;
}

function getDefaultPgbouncerValues(
  serviceName: string,
  dbName: string,
  dbUser: string,
  baseChartValues: BaseChartValues,
): Record<string, unknown> {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { overrides: _overrides, ...baseValues } = baseChartValues;

  return {
    ...baseValues,
    nameOverride: `pgbouncer-${serviceName}`,
    fullnameOverride: `pgbouncer-${serviceName}`,
    database: {
      host: `postgresql-${serviceName}`,
      port: 5432,
      name: dbName,
      user: dbUser,
    },
  };
}

function generatePgbouncerValuesForService(service: ServiceWithDatabase, baseChartValues: BaseChartValues): void {
  if (!service.database?.enabled) {
    return;
  }

  const serviceName = service.name;
  const dbName = service.database.name || `${serviceName.replace(/-/g, '_')}_db`;
  const dbUser = service.database.user || `${serviceName.replace(/-/g, '_')}_user`;

  console.log(`→ Generating PgBouncer values for service: ${serviceName}`);

  const environments: Array<'development' | 'production'> = ['development', 'production'];

  for (const env of environments) {
    let finalValues = getDefaultPgbouncerValues(serviceName, dbName, dbUser, baseChartValues);

    // Apply environment-specific overrides from base chart
    const baseChartEnvOverrides = baseChartValues.overrides?.[env] as Record<string, unknown> | undefined;
    if (baseChartEnvOverrides) {
      finalValues = deepMerge(finalValues, baseChartEnvOverrides);
    }

    const header = [
      '# This file is automatically generated and should not be edited manually!',
      `# Generated PgBouncer values for ${serviceName} in ${env} environment`,
      `# Database: ${dbName}`,
      `# User: ${dbUser}`,
      `# Upstream: postgresql-${serviceName}`,
      '',
    ].join('\n');

    const yamlContent = header + yaml.stringify(finalValues);

    const envDir = path.join(OVERRIDES_DIR, env);
    if (!fs.existsSync(envDir)) {
      fs.mkdirSync(envDir, { recursive: true });
    }

    const outputPath = path.join(envDir, `pgbouncer-${serviceName}.yaml`);
    fs.writeFileSync(outputPath, yamlContent, 'utf-8');
    console.log(`✓ Generated: ${path.relative(process.cwd(), outputPath)}`);
  }
}

export function generatePgbouncerValues(): void {
  console.log('→ Starting PgBouncer values generation process');

  const projectRoot = path.join(__dirname, '../../..');

  const baseChartValues = loadBaseChartValues(projectRoot);

  const servicesPath = path.join(__dirname, '../../../services.yaml');
  const servicesContent = fs.readFileSync(servicesPath, 'utf-8');
  const servicesConfig = yaml.parse(servicesContent);

  const allServices: ServiceWithDatabase[] = [
    ...(servicesConfig.services.nest || []),
    ...(servicesConfig.services.next || []),
    ...(servicesConfig.services.fastapi || []),
  ];

  const servicesWithDb = allServices.filter((s) => s.database?.enabled);

  console.log(`→ Found ${servicesWithDb.length} service(s) with database enabled:`);
  for (const service of servicesWithDb) {
    console.log(`→   • ${service.name} (${service.database?.name || `${service.name}_db`})`);
  }

  let generatedCount = 0;
  for (const service of servicesWithDb) {
    generatePgbouncerValuesForService(service, baseChartValues);
    generatedCount += 2; // development + production
  }

  console.log('→ Generation summary:');
  console.log(`✓   Total files generated: ${generatedCount}`);
}
