{{- if .Values.ingress.tls.enabled }}
# Этот Secret будет создан автоматически при первом запуске
# Или вы можете создать его вручную с помощью:
# kubectl create secret tls {{ .Values.ingress.tls.secretName }} --cert=certs/tls.crt --key=certs/tls.key -n {{ .Values.ingress.namespace }}
# 
# Для генерации самоподписного сертификата используйте скрипт:
# ./generate-tls-cert.sh
{{- end }}