image:
  repository: core-client-info

nameOverride: "core-client-info"
fullnameOverride: "core-client-info"

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

metrics:
  enabled: true
  port: 9464

env:
  PORT: "8000"
  PYTHON_ENV: "production"
  DB_HOST: "pgbouncer-core-client-info"
  DB_PORT: "5432"
  DB_NAME: "core_client_info_db"
  DB_USER: "core_client_info_user"
  CORE_AUTH_URL: http://core-auth.default.svc.cluster.local/core-auth

livenessProbe:
  httpGet:
    path: /core-client-info/status

readinessProbe:
  httpGet:
    path: /core-client-info/status

resources:
  limits:
    cpu: 350m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 300Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

overrides:
  production:
    canary:
      enabled: true
