name: Test E2E
description: 'Run e2e tests for provided services'

inputs:
  services:
    description: "Services name to test"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install netstat
      run: sudo apt-get update && sudo apt-get install -y net-tools
      shell: bash

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 9
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Install chromium
      run: pnpm --filter e2e exec playwright install chromium
      shell: bash

    - name: Test E2E
      run: |
        if [ -n "${{ inputs.services }}" ]; then
          pnpm --filter e2e run e2e ${{ inputs.services }}
        else
          pnpm --filter e2e run e2e
        fi
      shell: bash

