# Конфигурация для web-messages-ssr сервиса
# Используется при деплое через: helm install web-messages-ssr ./infra/helmcharts/frontend-service -f services/web-messages-ssr/service.yaml

image:
  repository: web-messages-ssr

nameOverride: "web-messages-ssr"
fullnameOverride: "web-messages-ssr"

service:
  type: ClusterIP
  port: 80
  targetPort: 3007

metrics:
  enabled: true
  port: 9464

env:
  PORT: "3007"
  NODE_ENV: "production"
  CORE_MESSAGES_URL: "http://core-messages.default.svc.cluster.local/core-messages"
  CORE_CLIENT_INFO_URL: "http://core-client-info.default.svc.cluster.local/core-client-info"
  CORE_AUTH_URL: "http://core-auth.default.svc.cluster.local/core-auth"
  FILES_STORAGE_URL: "http://system-files-storage.default.svc.cluster.local/system-files-storage"

resources:
  limits:
    cpu: 600m
    memory: 512Mi
  requests:
    cpu: 180m
    memory: 300Mi

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

overrides:
  production:
    canary:
      enabled: true
