import * as fs from 'node:fs';
import * as path from 'node:path';
import * as yaml from 'yaml';

const INFRA_DIR = path.join(__dirname, '../../');
const OVERRIDES_DIR = path.join(INFRA_DIR, 'overrides');

interface RedisServiceConfig {
  config?: Record<string, unknown>;
  persistence?: Record<string, unknown>;
  resources?: {
    production?: Record<string, unknown>;
    development?: Record<string, unknown>;
  };
}

function deepMerge(
  target: Record<string, unknown>,
  source: Record<string, unknown> | undefined,
): Record<string, unknown> {
  if (!source) return target;
  const result = { ...target };
  for (const key in source) {
    if (source[key] && typeof source[key] === 'object' && !Array.isArray(source[key])) {
      result[key] = deepMerge((target[key] as Record<string, unknown>) || {}, source[key] as Record<string, unknown>);
    } else if (source[key] !== undefined) {
      result[key] = source[key];
    }
  }
  return result;
}

function discoverRedisInstances(projectRoot: string): Array<{ name: string; config: RedisServiceConfig }> {
  const redisDir = path.join(projectRoot, 'infra/redis');
  if (!fs.existsSync(redisDir)) {
    return [];
  }

  const instances: Array<{ name: string; config: RedisServiceConfig }> = [];

  for (const entry of fs.readdirSync(redisDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const serviceYamlPath = path.join(redisDir, entry.name, 'service.yaml');
    if (!fs.existsSync(serviceYamlPath)) continue;

    const content = fs.readFileSync(serviceYamlPath, 'utf-8');
    const config = yaml.parse(content) as RedisServiceConfig;
    instances.push({ name: entry.name, config });
    console.log(`  ✓ Found Redis instance: ${entry.name}`);
  }

  return instances;
}

function buildFinalValues(
  instanceName: string,
  baseChartValues: Record<string, unknown>,
  serviceConfig: RedisServiceConfig,
  environment: 'development' | 'production',
): Record<string, unknown> {
  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const { overrides: _overrides, ...base } = baseChartValues as Record<string, unknown> & { overrides?: unknown };

  let result: Record<string, unknown> = {
    ...base,
    nameOverride: instanceName,
    fullnameOverride: instanceName,
  };

  // Apply base chart env overrides
  const baseChartEnvOverrides = (baseChartValues as Record<string, Record<string, unknown>>).overrides?.[environment];
  if (baseChartEnvOverrides) {
    result = deepMerge(result, baseChartEnvOverrides);
  }

  // Apply service.yaml config
  if (serviceConfig.config) {
    result.config = deepMerge((result.config as Record<string, unknown>) || {}, serviceConfig.config);
  }

  if (serviceConfig.persistence) {
    result.persistence = deepMerge((result.persistence as Record<string, unknown>) || {}, serviceConfig.persistence);
  }

  if (serviceConfig.resources) {
    const envResources = serviceConfig.resources[environment];
    if (envResources !== undefined) {
      result.resources = envResources;
    }
  }

  return result;
}

export function generateRedisValues(): void {
  console.log('→ Starting Redis values generation process');

  const projectRoot = path.join(__dirname, '../../..');
  const baseValuesPath = path.join(projectRoot, 'infra/helmcharts/redis/values.yaml');

  if (!fs.existsSync(baseValuesPath)) {
    throw new Error(`Base Redis chart values not found at: ${baseValuesPath}`);
  }

  const baseChartValues = yaml.parse(fs.readFileSync(baseValuesPath, 'utf-8')) as Record<string, unknown>;

  const instances = discoverRedisInstances(projectRoot);

  if (instances.length === 0) {
    console.log('⚠️  No Redis instances found in infra/redis/');
    return;
  }

  console.log(`→ Found ${instances.length} Redis instance(s):`);
  for (const { name } of instances) {
    console.log(`→   • ${name}`);
  }

  let generatedCount = 0;

  for (const { name, config } of instances) {
    const environments: Array<'development' | 'production'> = ['development', 'production'];

    for (const env of environments) {
      const finalValues = buildFinalValues(name, baseChartValues, config, env);

      const header = [
        '# This file is automatically generated and should not be edited manually!',
        `# Generated Redis values for ${name} in ${env} environment`,
        '',
      ].join('\n');

      const yamlContent = header + yaml.stringify(finalValues);

      const envDir = path.join(OVERRIDES_DIR, env);
      if (!fs.existsSync(envDir)) {
        fs.mkdirSync(envDir, { recursive: true });
      }

      const outputPath = path.join(envDir, `redis-${name}.yaml`);
      fs.writeFileSync(outputPath, yamlContent, 'utf-8');
      console.log(`✓ Generated: ${path.relative(process.cwd(), outputPath)}`);
      generatedCount++;
    }
  }

  console.log('→ Generation summary:');
  console.log(`✓   Total files generated: ${generatedCount}`);
}
