FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHON_ENV=production

COPY --from=ghcr.io/astral-sh/uv:latest /uv /usr/local/bin/uv

EXPOSE {{port}}

WORKDIR /app

COPY services/{{serviceName}}/pyproject.toml services/{{serviceName}}/uv.lock* ./

RUN uv sync --frozen --no-dev

COPY services/{{serviceName}}/app ./app

CMD ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "{{port}}"]
