{
 "title": "core-schedule Service Metrics",
 "tags": [
  "core-schedule",
  "opentelemetry",
  "fastapi",
  "python"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Timings (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.80, (rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\"}[5m])))) or on() vector(0)",
     "legendFormat": "P80"
    },
    {
     "expr": "sum(histogram_quantile(0.95, (rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\"}[5m])))) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "sum(histogram_quantile(0.99, (rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\"}[5m])))) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "OR RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\", http_status_code=~\"2..|3..\"}[1m])) by (http_status_code) or on() vector(0)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\", http_status_code=~\"[45]..\"}[1m]))  by (http_status_code) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By POD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Timings (ms) by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(histogram_quantile(0.80, (rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\"}[5m])))) by (pod) or on() vector(0)",
     "legendFormat": "P80 {{pod}}"
    },
    {
     "expr": "sum(histogram_quantile(0.95, (rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\"}[5m])))) by (pod) or on() vector(0)",
     "legendFormat": "P95 {{pod}}"
    },
    {
     "expr": "sum(histogram_quantile(0.99, (rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\"}[5m])))) by (pod) or on() vector(0)",
     "legendFormat": "P99 {{pod}}"
    }
   ]
  },
  {
   "title": "OR RPS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\", http_status_code=~\"2..|3..\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} from {{pod}}"
    }
   ]
  },
  {
   "title": "Bad RPS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\", http_status_code=~\"[45]..\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} by {{pod}}"
    }
   ]
  },
  { "title": "Python Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"core-schedule\"}",
     "legendFormat": "RSS {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"core-schedule\"}[1m])",
     "legendFormat": "CPU {{pod}}"
    }
   ]
  },
  { "title": "Routes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "GET /core-schedule/admin/classrooms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 }
  },
  {
   "title": "GET /core-schedule/admin/classrooms - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/classrooms - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/classrooms - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/classrooms",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 }
  },
  {
   "title": "POST /core-schedule/admin/classrooms - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/classrooms - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/classrooms - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/classrooms/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 }
  },
  {
   "title": "DELETE /core-schedule/admin/classrooms/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/classrooms/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"DELETE\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/classrooms/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"DELETE\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/classrooms/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 }
  },
  {
   "title": "GET /core-schedule/admin/classrooms/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/classrooms/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/classrooms/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/classrooms/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 }
  },
  {
   "title": "PUT /core-schedule/admin/classrooms/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/classrooms/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"PUT\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/classrooms/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/classrooms/:id\",http_method=\"PUT\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/overrides",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 113 }
  },
  {
   "title": "GET /core-schedule/admin/overrides - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/overrides - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/overrides - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 114 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/overrides",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 122 }
  },
  {
   "title": "POST /core-schedule/admin/overrides - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/overrides - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/overrides - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/overrides/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 131 }
  },
  {
   "title": "DELETE /core-schedule/admin/overrides/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/overrides/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"DELETE\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/overrides/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 132 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"DELETE\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/overrides/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 140 }
  },
  {
   "title": "PUT /core-schedule/admin/overrides/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/overrides/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"PUT\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/overrides/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/overrides/:id\",http_method=\"PUT\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/semesters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 149 }
  },
  {
   "title": "GET /core-schedule/admin/semesters - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/semesters - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/semesters - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/semesters",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 }
  },
  {
   "title": "POST /core-schedule/admin/semesters - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/semesters - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/semesters - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 159 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/semesters/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 167 }
  },
  {
   "title": "DELETE /core-schedule/admin/semesters/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/semesters/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"DELETE\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/semesters/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 168 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"DELETE\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/semesters/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 176 }
  },
  {
   "title": "GET /core-schedule/admin/semesters/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/semesters/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/semesters/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/semesters/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 185 }
  },
  {
   "title": "PUT /core-schedule/admin/semesters/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/semesters/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"PUT\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/semesters/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/semesters/:id\",http_method=\"PUT\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/session-events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 }
  },
  {
   "title": "GET /core-schedule/admin/session-events - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/session-events - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/session-events - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 195 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/session-events",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 203 }
  },
  {
   "title": "POST /core-schedule/admin/session-events - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/session-events - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/session-events - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 204 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/session-events/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 212 }
  },
  {
   "title": "DELETE /core-schedule/admin/session-events/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/session-events/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"DELETE\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/session-events/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 213 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"DELETE\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/session-events/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 221 }
  },
  {
   "title": "PUT /core-schedule/admin/session-events/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/session-events/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"PUT\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/session-events/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 222 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/session-events/:id\",http_method=\"PUT\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/teachers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 230 }
  },
  {
   "title": "GET /core-schedule/admin/teachers - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 231 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/teachers - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 231 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/teachers - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 231 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/teachers/sync",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 239 }
  },
  {
   "title": "POST /core-schedule/admin/teachers/sync - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers/sync\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers/sync\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers/sync\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/teachers/sync - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers/sync\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/teachers/sync - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 240 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/teachers/sync\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/templates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 248 }
  },
  {
   "title": "GET /core-schedule/admin/templates - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/templates - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/admin/templates - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 249 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/templates",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 257 }
  },
  {
   "title": "POST /core-schedule/admin/templates - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 258 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/templates - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 258 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/templates - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 258 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/templates/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 266 }
  },
  {
   "title": "DELETE /core-schedule/admin/templates/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 267 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/templates/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 267 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"DELETE\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-schedule/admin/templates/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 267 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"DELETE\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/templates/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 275 }
  },
  {
   "title": "PUT /core-schedule/admin/templates/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/templates/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"PUT\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "PUT /core-schedule/admin/templates/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 276 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/:id\",http_method=\"PUT\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/templates/bulk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 284 }
  },
  {
   "title": "POST /core-schedule/admin/templates/bulk - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 285 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/bulk\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/bulk\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/bulk\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/templates/bulk - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 285 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/bulk\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-schedule/admin/templates/bulk - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 285 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/admin/templates/bulk\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/groups/[^/]+/exams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 293 }
  },
  {
   "title": "GET /core-schedule/groups/:id/exams - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 294 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/exams\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/exams\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/exams\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/groups/:id/exams - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 294 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/exams\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/groups/:id/exams - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 294 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/exams\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/groups/[^/]+/schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 302 }
  },
  {
   "title": "GET /core-schedule/groups/:id/schedule - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 303 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/schedule\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/schedule\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/schedule\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/groups/:id/schedule - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 303 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/schedule\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/groups/:id/schedule - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 303 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/schedule\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/groups/[^/]+/template",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 311 }
  },
  {
   "title": "GET /core-schedule/groups/:id/template - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 312 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/template\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/template\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/template\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/groups/:id/template - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 312 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/template\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/groups/:id/template - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 312 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/groups/:id/template\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/teachers/[^/]+/exams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 320 }
  },
  {
   "title": "GET /core-schedule/teachers/:id/exams - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/exams\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/exams\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/exams\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/teachers/:id/exams - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/exams\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/teachers/:id/exams - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 321 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/exams\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/teachers/[^/]+/schedule",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 329 }
  },
  {
   "title": "GET /core-schedule/teachers/:id/schedule - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 330 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/schedule\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/schedule\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/schedule\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/teachers/:id/schedule - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 330 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/schedule\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/teachers/:id/schedule - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 330 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/schedule\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/teachers/[^/]+/template",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 338 }
  },
  {
   "title": "GET /core-schedule/teachers/:id/template - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 339 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/template\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/template\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/template\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-schedule/teachers/:id/template - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 339 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/template\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-schedule/teachers/:id/template - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 339 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-schedule\",http_target=\"/core-schedule/teachers/:id/template\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  }
 ]
}