{
 "title": "core-auth Service Metrics",
 "tags": [
  "core-auth",
  "opentelemetry",
  "fastapi",
  "python"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Timings (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target!=\"/core-auth/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target!=\"/core-auth/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target!=\"/core-auth/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "OR RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\", http_status_code=~\"2..|3..\", http_target!=\"/core-auth/status\"}[1m])) by (http_status_code) or on() vector(0)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\", http_status_code=~\"[45]..\", http_target!=\"/core-auth/status\"}[1m])) by (http_status_code) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By POD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Timings (ms) by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target!=\"/core-auth/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P80 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target!=\"/core-auth/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P95 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target!=\"/core-auth/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P99 {{pod}}"
    }
   ]
  },
  {
   "title": "OR RPS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\", http_status_code=~\"2..|3..\", http_target!=\"/core-auth/status\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} from {{pod}}"
    }
   ]
  },
  {
   "title": "Bad RPS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\", http_status_code=~\"[45]..\", http_target!=\"/core-auth/status\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} by {{pod}}"
    }
   ]
  },
  { "title": "Python Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"core-auth\"}",
     "legendFormat": "RSS {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"core-auth\"}[1m])",
     "legendFormat": "CPU {{pod}}"
    }
   ]
  },
  {
   "title": "Status Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status Checks - OK RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\", http_status_code=~\"2..|3..\", http_target=\"/core-auth/status\"}[1m])) by (http_status_code) or on() vector(0)",
       "legendFormat": "{{http_status_code}}"
      }
     ]
    },
    {
     "title": "Status Checks - Bad RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\", http_status_code=~\"[45]..\", http_target=\"/core-auth/status\"}[1m])) by (http_status_code) or on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Routes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  {
   "title": "GET /core-auth/auth/caldav-tokens",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 }
  },
  {
   "title": "GET /core-auth/auth/caldav-tokens - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/caldav-tokens - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/caldav-tokens - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/caldav-tokens",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }
  },
  {
   "title": "POST /core-auth/auth/caldav-tokens - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/caldav-tokens - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/caldav-tokens - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-auth/auth/caldav-tokens/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 }
  },
  {
   "title": "DELETE /core-auth/auth/caldav-tokens/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "DELETE /core-auth/auth/caldav-tokens/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens/:id\",http_method=\"DELETE\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-auth/auth/caldav-tokens/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/caldav-tokens/:id\",http_method=\"DELETE\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "POST /core-auth/auth/challenge", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "POST /core-auth/auth/challenge - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/challenge\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/challenge\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/challenge\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/challenge - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/challenge\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/challenge - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/challenge\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/challenge/[^/]+/check",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 }
  },
  {
   "title": "GET /core-auth/auth/challenge/:id/check - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/check\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/check\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/check\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/challenge/:id/check - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/check\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/challenge/:id/check - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/check\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/challenge/[^/]+/verify",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 }
  },
  {
   "title": "POST /core-auth/auth/challenge/:id/verify - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/verify\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/verify\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/verify\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/challenge/:id/verify - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/verify\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/challenge/:id/verify - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/challenge/:id/verify\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/forgot-password",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 }
  },
  {
   "title": "POST /core-auth/auth/forgot-password - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/forgot-password - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/forgot-password - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/forgot-password/[^/]+/reset",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 }
  },
  {
   "title": "POST /core-auth/auth/forgot-password/:id/reset - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/reset\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/reset\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/reset\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/forgot-password/:id/reset - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/reset\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/forgot-password/:id/reset - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/reset\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/forgot-password/[^/]+/verify",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 }
  },
  {
   "title": "POST /core-auth/auth/forgot-password/:id/verify - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/verify\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/verify\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/verify\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/forgot-password/:id/verify - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/verify\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/forgot-password/:id/verify - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/forgot-password/:id/verify\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/internal/caldav-tokens/validate/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 }
  },
  {
   "title": "GET /core-auth/auth/internal/caldav-tokens/validate/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/internal/caldav-tokens/validate/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/internal/caldav-tokens/validate/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/internal/caldav-tokens/validate/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/internal/caldav-tokens/validate/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/internal/caldav-tokens/validate/:id\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/internal/caldav-tokens/validate/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/internal/caldav-tokens/validate/:id\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "PATCH /core-auth/auth/internal/users/[^/]+/email",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 }
  },
  {
   "title": "PATCH /core-auth/auth/internal/users/:id/email - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/email\",http_method=\"PATCH\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/email\",http_method=\"PATCH\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/email\",http_method=\"PATCH\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PATCH /core-auth/auth/internal/users/:id/email - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/email\",http_method=\"PATCH\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "PATCH /core-auth/auth/internal/users/:id/email - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/email\",http_method=\"PATCH\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "PATCH /core-auth/auth/internal/users/[^/]+/password",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 }
  },
  {
   "title": "PATCH /core-auth/auth/internal/users/:id/password - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/password\",http_method=\"PATCH\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/password\",http_method=\"PATCH\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/password\",http_method=\"PATCH\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PATCH /core-auth/auth/internal/users/:id/password - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/password\",http_method=\"PATCH\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "PATCH /core-auth/auth/internal/users/:id/password - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/internal/users/:id/password\",http_method=\"PATCH\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "POST /core-auth/auth/login", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 } },
  {
   "title": "POST /core-auth/auth/login - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/login\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/login\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/login\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/login - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/login\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/login - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/login\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /core-auth/auth/me", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "GET /core-auth/auth/me - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/me\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/me\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/me\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/me - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/me\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/me - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/me\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "POST /core-auth/auth/register", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 } },
  {
   "title": "POST /core-auth/auth/register - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/register\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/register\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/register\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/register - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/register\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/register - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/register\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /core-auth/auth/sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 } },
  {
   "title": "GET /core-auth/auth/sessions - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/sessions\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/sessions\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/sessions\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/sessions - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/sessions\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-auth/auth/sessions - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/sessions\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-auth/auth/sessions/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 }
  },
  {
   "title": "DELETE /core-auth/auth/sessions/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/sessions/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/sessions/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/sessions/:id\",http_method=\"DELETE\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "DELETE /core-auth/auth/sessions/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/sessions/:id\",http_method=\"DELETE\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "DELETE /core-auth/auth/sessions/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/sessions/:id\",http_method=\"DELETE\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/validate-session",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 222 }
  },
  {
   "title": "POST /core-auth/auth/validate-session - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/validate-session\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/validate-session\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-auth\",http_target=\"/core-auth/auth/validate-session\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/validate-session - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/validate-session\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-auth/auth/validate-session - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-auth\",http_target=\"/core-auth/auth/validate-session\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  }
 ]
}