{
 "title": "core-client-info Service Metrics",
 "tags": [
  "core-client-info",
  "opentelemetry",
  "fastapi",
  "python"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Timings (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target!=\"/core-client-info/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target!=\"/core-client-info/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target!=\"/core-client-info/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "OR RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\", http_status_code=~\"2..|3..\", http_target!=\"/core-client-info/status\"}[1m])) by (http_status_code) or on() vector(0)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\", http_status_code=~\"[45]..\", http_target!=\"/core-client-info/status\"}[1m])) by (http_status_code) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By POD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Timings (ms) by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target!=\"/core-client-info/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P80 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target!=\"/core-client-info/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P95 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target!=\"/core-client-info/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P99 {{pod}}"
    }
   ]
  },
  {
   "title": "OR RPS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\", http_status_code=~\"2..|3..\", http_target!=\"/core-client-info/status\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} from {{pod}}"
    }
   ]
  },
  {
   "title": "Bad RPS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\", http_status_code=~\"[45]..\", http_target!=\"/core-client-info/status\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} by {{pod}}"
    }
   ]
  },
  { "title": "Python Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Memory (RSS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{service=\"core-client-info\"}",
     "legendFormat": "RSS {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"core-client-info\"}[1m])",
     "legendFormat": "CPU {{pod}}"
    }
   ]
  },
  {
   "title": "Status Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status Checks - OK RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\", http_status_code=~\"2..|3..\", http_target=\"/core-client-info/status\"}[1m])) by (http_status_code) or on() vector(0)",
       "legendFormat": "{{http_status_code}}"
      }
     ]
    },
    {
     "title": "Status Checks - Bad RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\", http_status_code=~\"[45]..\", http_target=\"/core-client-info/status\"}[1m])) by (http_status_code) or on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Routes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  { "title": "GET /core-client-info/debts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "GET /core-client-info/debts - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/debts\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/debts\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/debts\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/debts - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/debts\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/debts - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/debts\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "PATCH /core-client-info/debts/[^/]+/request-retake",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 }
  },
  {
   "title": "PATCH /core-client-info/debts/:id/request-retake - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/debts/:id/request-retake\",http_method=\"PATCH\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/debts/:id/request-retake\",http_method=\"PATCH\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/debts/:id/request-retake\",http_method=\"PATCH\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PATCH /core-client-info/debts/:id/request-retake - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/debts/:id/request-retake\",http_method=\"PATCH\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "PATCH /core-client-info/debts/:id/request-retake - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/debts/:id/request-retake\",http_method=\"PATCH\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/groups",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 }
  },
  {
   "title": "GET /core-client-info/profile/groups - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/groups\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/groups\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/groups\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/groups - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/groups\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/groups - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/groups\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/profile/init-user",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 }
  },
  {
   "title": "POST /core-client-info/profile/init-user - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/init-user\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/init-user\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/init-user\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-client-info/profile/init-user - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/init-user\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/profile/init-user - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/init-user\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/personal-data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 }
  },
  {
   "title": "GET /core-client-info/profile/personal-data - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/personal-data\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/personal-data\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/personal-data\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/personal-data - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/personal-data\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/personal-data - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/personal-data\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/profile/search-for-registration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 }
  },
  {
   "title": "POST /core-client-info/profile/search-for-registration - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/search-for-registration\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/search-for-registration\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/search-for-registration\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-client-info/profile/search-for-registration - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/search-for-registration\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/profile/search-for-registration - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/search-for-registration\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/user",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 }
  },
  {
   "title": "GET /core-client-info/profile/user - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/user\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/user\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/user\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/user - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/user\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/user - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/user\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/users-by-group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 }
  },
  {
   "title": "GET /core-client-info/profile/users-by-group - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/users-by-group\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/users-by-group\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/users-by-group\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/users-by-group - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/users-by-group\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/users-by-group - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/users-by-group\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/profile/users/batch",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 }
  },
  {
   "title": "POST /core-client-info/profile/users/batch - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/batch\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/batch\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/batch\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-client-info/profile/users/batch - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/batch\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/profile/users/batch - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/batch\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/users/search",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 }
  },
  {
   "title": "GET /core-client-info/profile/users/search - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/search\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/search\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/search\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/users/search - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/search\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/profile/users/search - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/profile/users/search\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/achievements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 }
  },
  {
   "title": "GET /core-client-info/rating/achievements - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/achievements\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/achievements\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/achievements\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/achievements - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/achievements\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/achievements - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/achievements\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/grade-improvements",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 }
  },
  {
   "title": "GET /core-client-info/rating/grade-improvements - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/grade-improvements\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/grade-improvements\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/grade-improvements\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/grade-improvements - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/grade-improvements\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/grade-improvements - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/grade-improvements\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/grades",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 }
  },
  {
   "title": "GET /core-client-info/rating/grades - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/grades\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/grades\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/grades\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/grades - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/grades\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/grades - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/grades\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 }
  },
  {
   "title": "GET /core-client-info/rating/level - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/level\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/level\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/level\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/level - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/level\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/level - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/level\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/rankings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 }
  },
  {
   "title": "GET /core-client-info/rating/rankings - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/rankings\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/rankings\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/rankings\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/rankings - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/rankings\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/rankings - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 196 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/rankings\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 204 }
  },
  {
   "title": "GET /core-client-info/rating/stats - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/stats\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/stats\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/stats\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/stats - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/stats\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/stats - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 205 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/stats\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/streak",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 213 }
  },
  {
   "title": "GET /core-client-info/rating/streak - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/streak\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/streak\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/rating/streak\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/streak - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/streak\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/rating/streak - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 214 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/rating/streak\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /core-client-info/settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 222 } },
  {
   "title": "GET /core-client-info/settings - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/settings - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/settings - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 223 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "PUT /core-client-info/settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 231 } },
  {
   "title": "PUT /core-client-info/settings - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"PUT\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "PUT /core-client-info/settings - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"PUT\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "PUT /core-client-info/settings - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 232 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/settings\",http_method=\"PUT\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/settings/email",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 240 }
  },
  {
   "title": "POST /core-client-info/settings/email - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings/email\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings/email\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings/email\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-client-info/settings/email - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/settings/email\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/settings/email - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 241 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/settings/email\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/settings/password",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 249 }
  },
  {
   "title": "POST /core-client-info/settings/password - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings/password\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings/password\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/settings/password\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-client-info/settings/password - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/settings/password\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/settings/password - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 250 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/settings/password\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/subjects/choices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 258 }
  },
  {
   "title": "GET /core-client-info/subjects/choices - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 259 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/subjects/choices - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 259 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/subjects/choices - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 259 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/subjects/choices-with-priorities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 267 }
  },
  {
   "title": "GET /core-client-info/subjects/choices-with-priorities - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 268 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices-with-priorities\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices-with-priorities\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices-with-priorities\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/subjects/choices-with-priorities - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 268 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices-with-priorities\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/subjects/choices-with-priorities - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 268 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/subjects/choices-with-priorities\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/subjects/save-priorities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 276 }
  },
  {
   "title": "POST /core-client-info/subjects/save-priorities - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 277 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/save-priorities\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/save-priorities\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/save-priorities\",http_method=\"POST\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "POST /core-client-info/subjects/save-priorities - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 277 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/subjects/save-priorities\",http_method=\"POST\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "POST /core-client-info/subjects/save-priorities - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 277 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/subjects/save-priorities\",http_method=\"POST\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/subjects/user-priorities/[^/]+",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 285 }
  },
  {
   "title": "GET /core-client-info/subjects/user-priorities/:id - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 286 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/user-priorities/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/user-priorities/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_milliseconds_bucket{service=\"core-client-info\",http_target=\"/core-client-info/subjects/user-priorities/:id\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /core-client-info/subjects/user-priorities/:id - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 286 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/subjects/user-priorities/:id\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /core-client-info/subjects/user-priorities/:id - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 286 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_milliseconds_count{service=\"core-client-info\",http_target=\"/core-client-info/subjects/user-priorities/:id\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  }
 ]
}