{
 "title": "web-profile-ssr Service Metrics",
 "tags": [
  "web-profile-ssr",
  "opentelemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Timings (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route!=\"/api/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route!=\"/api/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route!=\"/api/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "OR RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\", http_status_code=~\"2..|3..\", http_route!=\"/api/status\"}[1m])) by (http_status_code) or on() vector(0)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Bad RPS ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\", http_status_code=~\"[45]..\", http_route!=\"/api/status\"}[1m])) by (http_status_code) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By POD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Timings (ms) by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route!=\"/api/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P80 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route!=\"/api/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P95 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route!=\"/api/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P99 {{pod}}"
    }
   ]
  },
  {
   "title": "OR PRS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\", http_status_code=~\"2..|3..\", http_route!=\"/api/status\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} from {{pod}}"
    }
   ]
  },
  {
   "title": "Bad RPS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\", http_status_code=~\"[45]..\", http_route!=\"/api/status\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} by {{pod}}"
    }
   ]
  },
  { "title": "Node JS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Event Loop Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(nodejs_eventloop_utilization{service=\"web-profile-ssr\"}) by (pod) or on() vector(0)",
     "legendFormat": "Event Loop Utilization {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(v8js_memory_heap_used{service=\"web-profile-ssr\"}) by (pod) or on() vector(0)",
     "legendFormat": "Heap Used {{pod}}"
    },
    {
     "expr": "sum(v8js_memory_heap_limit{service=\"web-profile-ssr\"}) by (pod) or on() vector(0)",
     "legendFormat": "Heap Limit {{pod}}"
    }
   ]
  },
  {
   "title": "Status Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status Checks - OK RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\", http_status_code=~\"2..|3..\", http_route=\"/api/status\"}[1m])) by (http_status_code) or on() vector(0)",
       "legendFormat": "{{http_status_code}}"
      }
     ]
    },
    {
     "title": "Status Checks - Bad RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\", http_status_code=~\"[45]..\", http_route=\"/api/status\"}[1m])) by (http_status_code) or on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Routes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  { "title": "GET /api/timeout-check", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "GET /api/timeout-check - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/api/timeout-check\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/api/timeout-check\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/api/timeout-check\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /api/timeout-check - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/api/timeout-check\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /api/timeout-check - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/api/timeout-check\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /api/undefined-url", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "GET /api/undefined-url - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/api/undefined-url\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/api/undefined-url\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/api/undefined-url\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /api/undefined-url - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/api/undefined-url\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /api/undefined-url - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/api/undefined-url\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "GET /profile - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile/data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "GET /profile/data - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/data\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/data\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/data\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/data - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/data\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/data - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/data\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile/dormitory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "GET /profile/dormitory - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/dormitory\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/dormitory\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/dormitory\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/dormitory - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/dormitory\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/dormitory - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/dormitory\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile/orders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 114 } },
  {
   "title": "GET /profile/orders - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/orders\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/orders\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/orders\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/orders - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/orders\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/orders - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 115 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/orders\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile/rating", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 } },
  {
   "title": "GET /profile/rating - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/rating\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/rating\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/rating\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/rating - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/rating\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/rating - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 124 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/rating\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile/references", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 132 } },
  {
   "title": "GET /profile/references - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/references\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/references\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/references\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/references - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/references\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/references - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/references\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile/scholarship", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 141 } },
  {
   "title": "GET /profile/scholarship - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/scholarship\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/scholarship\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/scholarship\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/scholarship - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/scholarship\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/scholarship - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/scholarship\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile/scolarship", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 150 } },
  {
   "title": "GET /profile/scolarship - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/scolarship\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/scolarship\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/scolarship\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/scolarship - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/scolarship\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/scolarship - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 151 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/scolarship\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile/settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "GET /profile/settings - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/settings\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/settings\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/settings\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/settings - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/settings\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/settings - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/settings\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /profile/settings/change-email",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 }
  },
  {
   "title": "GET /profile/settings/change-email - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-email\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-email\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-email\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/settings/change-email - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-email\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/settings/change-email - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-email\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  {
   "title": "GET /profile/settings/change-password",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 177 }
  },
  {
   "title": "GET /profile/settings/change-password - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-password\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-password\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-password\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/settings/change-password - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-password\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/settings/change-password - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/settings/change-password\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /profile/subjects-ranking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 186 } },
  {
   "title": "GET /profile/subjects-ranking - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/subjects-ranking\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/subjects-ranking\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-profile-ssr\",http_route=\"/profile/subjects-ranking\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /profile/subjects-ranking - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/subjects-ranking\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /profile/subjects-ranking - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 187 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-profile-ssr\",http_route=\"/profile/subjects-ranking\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  }
 ]
}