{
 "title": "web-documents-ssr Service Metrics",
 "tags": [
  "web-documents-ssr",
  "opentelemetry"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Timings (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route!=\"/api/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P80"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route!=\"/api/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route!=\"/api/status\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "OR RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\", http_status_code=~\"2..|3..\", http_route!=\"/api/status\"}[1m])) by (http_status_code) or on() vector(0)",
     "legendFormat": "{{http_status_code}}"
    }
   ]
  },
  {
   "title": "Bad RPS ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\", http_status_code=~\"[45]..\", http_route!=\"/api/status\"}[1m])) by (http_status_code) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "By POD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Timings (ms) by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "histogram_quantile(0.80, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route!=\"/api/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P80 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route!=\"/api/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P95 {{pod}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route!=\"/api/status\"}[5m])) by (le, pod)) or on() vector(0)",
     "legendFormat": "P99 {{pod}}"
    }
   ]
  },
  {
   "title": "OR PRS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\", http_status_code=~\"2..|3..\", http_route!=\"/api/status\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} from {{pod}}"
    }
   ]
  },
  {
   "title": "Bad RPS by pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 42 },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\", http_status_code=~\"[45]..\", http_route!=\"/api/status\"}[1m])) by (http_status_code, pod) or on() vector(0)",
     "legendFormat": "{{http_status_code}} by {{pod}}"
    }
   ]
  },
  { "title": "Node JS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Event Loop Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(nodejs_eventloop_utilization{service=\"web-documents-ssr\"}) by (pod) or on() vector(0)",
     "legendFormat": "Event Loop Utilization {{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(v8js_memory_heap_used{service=\"web-documents-ssr\"}) by (pod) or on() vector(0)",
     "legendFormat": "Heap Used {{pod}}"
    },
    {
     "expr": "sum(v8js_memory_heap_limit{service=\"web-documents-ssr\"}) by (pod) or on() vector(0)",
     "legendFormat": "Heap Limit {{pod}}"
    }
   ]
  },
  {
   "title": "Status Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status Checks - OK RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\", http_status_code=~\"2..|3..\", http_route=\"/api/status\"}[1m])) by (http_status_code) or on() vector(0)",
       "legendFormat": "{{http_status_code}}"
      }
     ]
    },
    {
     "title": "Status Checks - Bad RPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\", http_status_code=~\"[45]..\", http_route=\"/api/status\"}[1m])) by (http_status_code) or on() vector(0)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Routes Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 } },
  { "title": "GET /documents/attestation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "GET /documents/attestation - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/attestation\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/attestation\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/attestation\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /documents/attestation - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\",http_route=\"/documents/attestation\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /documents/attestation - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\",http_route=\"/documents/attestation\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /documents/debts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "GET /documents/debts - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/debts\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/debts\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/debts\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /documents/debts - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\",http_route=\"/documents/debts\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /documents/debts - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\",http_route=\"/documents/debts\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /documents/gradebook", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "GET /documents/gradebook - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/gradebook\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/gradebook\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/gradebook\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /documents/gradebook - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\",http_route=\"/documents/gradebook\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /documents/gradebook - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\",http_route=\"/documents/gradebook\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  },
  { "title": "GET /documents/student-id-card", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "GET /documents/student-id-card - Timings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/student-id-card\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/student-id-card\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_duration_bucket{service=\"web-documents-ssr\",http_route=\"/documents/student-id-card\",http_method=\"GET\"}[5m])) by (le)) or on() vector(0)",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "GET /documents/student-id-card - OK RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\",http_route=\"/documents/student-id-card\",http_method=\"GET\",http_status_code=~\"2..|3..\"}[1m])) or on() vector(0)",
     "legendFormat": "OK (2xx/3xx)"
    }
   ]
  },
  {
   "title": "GET /documents/student-id-card - Bad RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_duration_count{service=\"web-documents-ssr\",http_route=\"/documents/student-id-card\",http_method=\"GET\",http_status_code=~\"[45]..\"}[1m])) or on() vector(0)",
     "legendFormat": "Errors (4xx/5xx)"
    }
   ]
  }
 ]
}