apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgresql.fullname" . }}-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  POSTGRES_USER: {{ .Values.database.user | b64enc | quote }}
  POSTGRES_DB: {{ .Values.database.name | b64enc | quote }}

