config:
  maxmemory: "128mb"
  maxmemoryPolicy: "volatile-lru"
  loglevel: "notice"

persistence:
  enabled: false

resources:
  production:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 32Mi
  development:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 16Mi
