apiVersion: v2
name: mychart
description: ingress using nginx for my application
version: 0.1.0
dependencies:
  - name: ingress-nginx
    version: 4.14.0
    repository: https://kubernetes.github.io/ingress-nginx
