ingress-nginx:
  controller:
    replicaCount: 2
    allowSnippetAnnotations: true
    admissionWebhooks:
      enabled: false
    metrics:
      enabled: true
      port: 10254
      portName: metrics
      service:
        enabled: true
        servicePort: 10254
        type: ClusterIP
    config:
      use-http2: "true"
      http2-max-field-size: 16k
      http2-max-header-size: 32k
      proxy-connect-timeout: "3"
      proxy-read-timeout: "3"
      proxy-send-timeout: "3"
      limit-req-status-code: "429"
      log-format-upstream: $remote_addr - $http_x_forwarded_for - $remote_user
        [$time_local] "$request" $status $body_bytes_sent "$http_referer"
        "$http_user_agent" $request_length $request_time [$proxy_upstream_name]
        [$proxy_alternative_upstream_name] $upstream_addr
        $upstream_response_length $upstream_response_time $upstream_status
        $req_id
ingress:
  enabled: true
  name: ingress-main
  namespace: default
  catchallBackend:
    service: web-news-ssr
    port: 80
  tls:
    enabled: true
    secretName: supreme-tls-cert
    hosts:
      - sewaca.ru
      - diploma.sewaca.ru
      - tastefood.sewaca.ru
  rules:
    - service: core-applications
      port: 80
      type: fastapi
      paths:
        - path: /core-applications/orders/[^/]+/pdf
          method: GET
        - path: /core-applications/references/[^/]+/pdf
          method: GET
    - service: core-auth
      port: 80
      type: fastapi
      paths:
        - path: /core-auth/auth/login
          method: POST
        - path: /core-auth/auth/lookup
          method: POST
        - path: /core-auth/auth/me
          method: GET
        - path: /core-auth/auth/register
          method: POST
        - path: /core-auth/auth/validate-session
          method: POST
      rateLimit:
        rps: 3
        burstMultiplier: 1
    - service: core-client-info
      port: 80
      type: fastapi
      paths:
        - path: /core-client-info/attestations
          method: GET
        - path: /core-client-info/debts
          method: GET
        - path: /core-client-info/debts/[^/]+/request-retake
          method: PATCH
        - path: /core-client-info/profile/users-by-group
          method: GET
        - path: /core-client-info/profile/users/search
          method: GET
    - service: core-messages
      port: 80
      type: fastapi
      paths:
        - path: /core-messages/conversations/[^/]+/messages
          method: POST
        - path: /core-messages/conversations/[^/]+/messages/[^/]+
          method: DELETE
        - path: /core-messages/conversations/[^/]+/messages/[^/]+
          method: PATCH
        - path: /core-messages/conversations/[^/]+/messages/read
          method: POST
        - path: /core-messages/conversations/unread-count
          method: GET
        - path: /core-messages/conversations/updates
          method: GET
        - path: /core-messages/files
          method: POST
        - path: /core-messages/users/search
          method: GET
        - path: /core-messages/ws
          method: GET
      extraAnnotations:
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    - service: core-schedule
      port: 80
      type: fastapi
      paths:
        - path: /core-schedule/caldav/[^/]+/groups/[^/]+/calendar.ics
          method: GET
        - path: /core-schedule/caldav/[^/]+/teachers/[^/]+/calendar.ics
          method: GET
    - service: system-files-storage
      port: 80
      type: fastapi
      paths:
        - path: /system-files-storage/upload
          method: POST
      extraAnnotations:
        nginx.ingress.kubernetes.io/proxy-body-size: 20m
    - service: web-auth-ssr
      port: 80
      type: next
      paths:
        - path: /forgot-password
          method: GET
        - path: /login
          method: GET
        - path: /register
          method: GET
        - path: /web-auth-ssr/.*
          method: GET
    - service: web-documents-ssr
      port: 80
      type: next
      paths:
        - path: /documents/attestation
          method: GET
        - path: /documents/debts
          method: GET
        - path: /documents/gradebook
          method: GET
        - path: /documents/student-id-card
          method: GET
        - path: /web-documents-ssr/.*
          method: GET
    - service: web-messages-ssr
      port: 80
      type: next
      paths:
        - path: /api/messages/history
          method: GET
        - path: /messages
          method: GET
        - path: /messages/[^/]+
          method: GET
        - path: /messages/broadcast
          method: GET
        - path: /messages/broadcast/new
          method: GET
        - path: /messages/new
          method: GET
        - path: /messages/search
          method: GET
        - path: /web-messages-ssr/.*
          method: GET
    - service: web-news-ssr
      port: 80
      type: next
      paths:
        - path: /
          method: GET
          pathType: Exact
        - path: /news
          method: GET
        - path: /web-news-ssr/.*
          method: GET
    - service: web-profile-ssr
      port: 80
      type: next
      paths:
        - path: /api/timeout-check
          method: GET
        - path: /api/undefined-url
          method: GET
        - path: /profile
          method: GET
        - path: /profile/data
          method: GET
        - path: /profile/dormitory
          method: GET
        - path: /profile/orders
          method: GET
        - path: /profile/rating
          method: GET
        - path: /profile/references
          method: GET
        - path: /profile/scholarship
          method: GET
        - path: /profile/scolarship
          method: GET
        - path: /profile/settings
          method: GET
        - path: /profile/settings/change-email
          method: GET
        - path: /profile/settings/change-password
          method: GET
        - path: /profile/subjects-ranking
          method: GET
        - path: /web-profile-ssr/.*
          method: GET
    - service: web-schedule-ssr
      port: 80
      type: next
      paths:
        - path: /api/caldav-setup
          method: POST
        - path: /api/schedule
          method: GET
        - path: /schedule
          method: GET
        - path: /schedule/exams
          method: GET
        - path: /schedule/group
          method: GET
        - path: /schedule/teacher
          method: GET
        - path: /web-schedule-ssr/.*
          method: GET
    - service: minio
      port: 9000
      type: fastapi
      paths:
        - path: /storage/s3/(.*)
          method: GET
      extraAnnotations:
        nginx.ingress.kubernetes.io/rewrite-target: /messages-attachments/$1
