ingress-nginx:
  controller:
    replicaCount: 2
    allowSnippetAnnotations: true
    config:
      use-http2: "true"
      http2-max-field-size: 16k
      http2-max-header-size: 32k
ingress:
  enabled: true
  name: ingress-main
  namespace: default
  tls:
    enabled: true
    secretName: supreme-tls-cert
    hosts:
      - sewaca.ru
      - diploma.sewaca.ru
      - tastefood.sewaca.ru
  rules:
    - service: auth-ssr
      port: 80
      type: next
      paths:
        - path: /auth-ssr/.*
          method: GET
        - path: /login
          method: GET
        - path: /profile-old
          method: GET
        - path: /profile-old/[^/]+
          method: GET
        - path: /register
          method: GET
    - service: core-auth-bff
      port: 80
      type: nest
      paths:
        - path: /core-auth-bff/api/status
          method: GET
        - path: /core-auth-bff/auth/login
          method: POST
        - path: /core-auth-bff/auth/me
          method: GET
        - path: /core-auth-bff/auth/register
          method: POST
        - path: /core-auth-bff/auth/users/[^/]+
          method: GET
        - path: /core-auth-bff/auth/users/[^/]+
          method: DELETE
    - service: core-client-info
      port: 80
      type: fastapi
      paths:
        - path: /core-client-info/.*
          method: GET
        - path: /core-client-info/[^/]+
          method: GET
        - path: /core-client-info/[^/]+
          method: GET
        - path: /core-client-info/[^/]+/cancel
          method: POST
        - path: /core-client-info/[^/]+/extend-storage
          method: POST
        - path: /core-client-info/[^/]+/pdf
          method: GET
        - path: /core-client-info/[^/]+/pdf
          method: GET
        - path: /core-client-info/achievements
          method: GET
        - path: /core-client-info/choices
          method: GET
        - path: /core-client-info/counts
          method: GET
        - path: /core-client-info/email
          method: POST
        - path: /core-client-info/grade-improvements
          method: GET
        - path: /core-client-info/grades
          method: GET
        - path: /core-client-info/level
          method: GET
        - path: /core-client-info/order
          method: POST
        - path: /core-client-info/parent-agreement
          method: POST
        - path: /core-client-info/password
          method: POST
        - path: /core-client-info/personal-data
          method: GET
        - path: /core-client-info/rankings
          method: GET
        - path: /core-client-info/save-priorities
          method: POST
        - path: /core-client-info/stats
          method: GET
        - path: /core-client-info/streak
          method: GET
        - path: /core-client-info/user
          method: GET
        - path: /core-client-info/user-priorities/[^/]+
          method: GET
    - service: core-recipes-bff
      port: 80
      type: nest
      paths:
        - path: /core-recipes-bff/api/status
          method: GET
        - path: /core-recipes-bff/recipes
          method: GET
        - path: /core-recipes-bff/recipes/[^/]+
          method: GET
        - path: /core-recipes-bff/recipes/[^/]+
          method: PUT
        - path: /core-recipes-bff/recipes/[^/]+
          method: DELETE
        - path: /core-recipes-bff/recipes/[^/]+/like
          method: POST
        - path: /core-recipes-bff/recipes/propose
          method: POST
        - path: /core-recipes-bff/recipes/proposed/[^/]+/publish
          method: POST
        - path: /core-recipes-bff/recipes/proposed/all
          method: GET
    - service: frontend
      port: 80
      type: next
      paths:
        - path: /
          method: GET
        - path: /frontend/.*
          method: GET
        - path: /proposed-recipes
          method: GET
        - path: /recipes/[^/]+
          method: GET
        - path: /submit-recipe
          method: GET
    - service: web-profile-ssr
      port: 80
      type: next
      paths:
        - path: /api/undefined-url
          method: GET
        - path: /profile
          method: GET
        - path: /profile/data
          method: GET
        - path: /profile/dormitory
          method: GET
        - path: /profile/orders
          method: GET
        - path: /profile/rating
          method: GET
        - path: /profile/references
          method: GET
        - path: /profile/settings
          method: GET
        - path: /profile/subjects-ranking
          method: GET
        - path: /web-profile-ssr/.*
          method: GET
