image:
  repository: system-files-storage

nameOverride: "system-files-storage"
fullnameOverride: "system-files-storage"

replicas: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8007

metrics:
  enabled: true
  port: 9464

env:
  PORT: "8007"
  PYTHON_ENV: "production"

livenessProbe:
  httpGet:
    path: /core-files/api/status

readinessProbe:
  httpGet:
    path: /core-files/api/status

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 150m
    memory: 300Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

overrides:
  production:
    canary:
      enabled: true
